### ISSUE TITLE
Missing support for other countries

### ISSUE THREAD

**Issue by Padarom** [austintoddj/Canvas#10]
Two things I've noticed are currently US specific and don't work for other countries:

- Phone number formats
- State

While it is usual to specify the state in the US, this is not the case for every country. I live in Germany and here we mostly omit the state in our address. Also there's no commonly known two-character abbreviation for our states, so even though I put in "BY" (for Bavaria/Bayern) this might not be understood by everyone.

I suggest removing the state as a required field and adding a country field to the user profile. As for the phone number I don't have a clear solution in mind, perhaps it should just be taken care of by the admin/developer of the blog.

**Comment by austintoddj** [comment]
Thanks for the feedback! I'll try implementing these changes and release an update in a day or so. Stay tuned!
