### ISSUE TITLE
admin navbar covers modal

### ISSUE THREAD

**Issue by Shaun2D2** [austintoddj/canvas#100]
I noticed the modal in the admin console is partially being covered by the navbar, likely a z-index issue.  I'm using chrome 51.0.2704.103 (64-bit)

![image](https://cloud.githubusercontent.com/assets/3941040/17464392/1588e014-5c92-11e6-83e2-32c082274a33.png)

**Comment by austintoddj** [comment]
@Shaun2D2 Thanks for catching this. Looking into it ASAP.

**Comment by Shaun2D2** [comment]
@austintoddj np!  I'd be happy to take a look over it and submit a PR if you'd like.

**Comment by austintoddj** [comment]
@Shaun2D2 Yeah that'd be great if you want to go ahead and do that. Love to have your contributions to the project.
