### ISSUE TITLE
Canvas UI is not accessible

### ISSUE THREAD

**Issue by LukaSikic** [austintoddj/canvas#1010]
After following the documentation on how to install Canvas UI and trying to access /canvas-ui, user is being redirected to the login screen. CANVAS_PATH is set to null.

**Comment by austintoddj** [comment]
Looks like you got it sorted out @LukaSikic.

Just to follow-up: you will be restricted by setting the `CANVAS_PATH` variable to **null**. Per the config file:

```php
/*
|--------------------------------------------------------------------------
| Base Path
|--------------------------------------------------------------------------
|
| This is the URI where Canvas will be accessible from. If the path
| is set to null, Canvas will reside under the same path name as
| the application. Otherwise, this is used as the base path.
|
*/
```

If you do want to keep Canvas and it's frontend UI in the same app/domain, you'll need to keep this variable set at anything other than **null**.
