### ISSUE TITLE
Bullet and Numbering

### ISSUE THREAD

**Issue by somato-tomato** [austintoddj/canvas#1011]
Can i use bullet and numbering ?
Thank you.

**Comment by austintoddj** [comment]
You can use both bullets and numbering in the editor.

<img width="1337" alt="Screen Shot 2021-12-17 at 9 03 26 AM" src="https://user-images.githubusercontent.com/8037011/146564509-850bfff7-7b92-4c97-9572-52a9a43b9715.png">

**Comment by somato-tomato** [comment]
Hello,

Sorry but how to create like that i tried but to search the option but i cant find it. or i need to use embed code ? Thank you sir.

**Comment by austintoddj** [comment]
Nope, all you need to do is use the `-` (dash) or `1` (number) in the editor. Hitting `Enter` to a new line takes the list and continues it as either ordered or unordered.
