### ISSUE TITLE
AWS s3 setup failure 

### ISSUE THREAD

**Issue by james-wong123** [austintoddj/canvas#1012]
Anyone here know how to setup s3 for CANVAS ?

In my `config/canvas.php` 
'`storage_disk' => env('CANVAS_STORAGE_DISK', 's3'),`

I configure the information in `.env`

I filled the 
```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_BUCKET
AWS_DEFAULT_REGION
AWS_ENDPOINT
```

but I got status code `500` when I upload the images for profile.

**Comment by kusman28** [comment]
Hey @jameswong3388 how did u resolved this issue?
