### ISSUE TITLE
How to start editing the front end of canvas-ui 

### ISSUE THREAD

**Issue by james-wong123** [austintoddj/canvas#1013]
I am new to laravel, vue and canvas, I would like to know where to start if I want to edit like to logo etc.

**Comment by nielsphp** [comment]
All Vue components and pages that are rendered by the Canvas-UI are located in [canvas/resources/js/ui](https://github.com/austintoddj/canvas/tree/51fca4666483e2afd0b546867d3e926d3a3ac3e8/resources/js/ui)-folder. The Blade-template can be found at [canvas/resources/views/ui.blade.php](https://github.com/austintoddj/canvas/blob/51fca4666483e2afd0b546867d3e926d3a3ac3e8/resources/views/ui.blade.php). In these files you can customise the Canvas UI completely.

**Comment by james-wong123** [comment]
Erm, It doesn't seem to change anything when made some changes in `ui/views/AllPosts.vue` 😊

**Comment by nielsphp** [comment]
Yes, sorry I forgot to mention that. Did you follow the [instructions for installing Canvas:UI](https://github.com/austintoddj/canvas#canvas-ui)? This Artisan command copies the files mentioned by me to the resources folder of your own project. So, you can find these files in the folder 'yourproject/resources'. Here, you can edit the file 'yourproject/resources/js/canvas-views/AllPosts.vue'. After every change, the JS file has to be generated again, which you can do with the command 'npm run dev' (Using NPM) or 'yarn dev' (Using Yarn).

**Comment by james-wong123** [comment]
@nielsphp, so basically after you made changes in `yourproject/resources/js/canvas-views` , you run `npm run dev` ?

**Comment by nielsphp** [comment]
Yes. becasue `npm run dev` will combine all Vue-components, Vue-pages and other JS-scripts into one JS-file, which can be executed by the browser. To understand how this works, I would reccommend to read the documentation of [Webpack ](https://webpack.js.org/) and [Laravel Mix](https://laravel.com/docs/8.x/mix). 

If you make many changes, you can also run the command 'npm run watch'. This command will then generate the JS file every time you save a file that is part of your Vue application.

**Comment by james-wong123** [comment]
```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.entry['/js/canvas-ui'] should not contain the item 'C:\Users\User\PhpstormProjects\Blog\resources\js\canvas-ui\app.js' twice.
   -> All modules are loaded upon startup. The last one is exported.
```

I got this error pops out when I run `npm run dev`

**Comment by james-wong123** [comment]
Hi sry for asking question again 🤣, if I want to change interface of `Canvas` instead of `canvas-ui` do I use the same method as well?
