### ISSUE TITLE
SQL error when running Canvas

### ISSUE THREAD

**Issue by farez** [austintoddj/canvas#1022]
Hi!

I'm just installing Canvas but when I login it redirects to /canvas I get the following SQL error:

```
Illuminate\Database\QueryException
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 1 (SQL: update `sessions` set `payload` = YTo0OntzOjY6Il90b2tlbiI7czo0MDoiM3cxTlE5bXRHeGU2NTE2NVNncnVlRTJuc1N3Sk1oYmR3RHRwVGI1UiI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MzM6Imh0dHBzOi8vbm90aW9uaW52b2ljZS50ZXN0L2NhbnZhcyI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6NTM6ImxvZ2luX2NhbnZhc181OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtzOjM2OiI2YWQyNTIyYy1jOGE5LTQ1YWEtOWMzOC1iZWY5YzAwMGM2ZTIiO30=, `last_activity` = 1646904793, `user_id` = 6ad2522c-c8a9-45aa-9c38-bef9c000c6e2, `ip_address` = 127.0.0.1, `user_agent` = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 where `id` = xWh5H46YehplHjkjjz3KQJYZWOk3qH4YYPDOXPuz)
```

It looks like Canvas is trying to insert a string into the user_id field of the session table, which is a BIGINT field.

<img width="240" alt="Screenshot 2022-03-10 at 5 39 49 PM" src="https://user-images.githubusercontent.com/39633/157634431-1c8cb306-2487-4627-aff0-b0840a86b05a.png">

Steps to reproduce:
1. Run `composer require austintoddj/canvas`.
2. Run `php artisan canvas:install`.
3. Go to /canvas/login and login with 'email@example.com' and 'password'.
4. SQL error is thrown.

Laravel version: 8.54

**Comment by austintoddj** [comment]
@farez #851 Might have some solutions for you. Let me know if you're still stuck after checking that thread out and I can guide further.
