### ISSUE TITLE
I tried to install canvas again and for somereason teamtnt/tntsearch ext doing problems

### ISSUE THREAD

**Issue by orenguyster** [austintoddj/canvas#103]
Check it out, dont get it why it;s forced me to enabled sqlite3

https://i.imgur.com/WdCL0ia.png

**Comment by fergthh** [comment]
Hi @orenguyster! **Tntsearch** require this because uses it to indexing of the posts.

**Comment by austintoddj** [comment]
@orenguyster Like @fergthh stated, Canvas utilizes TNTSearch which relies on the Sqlite PHP extension. If you need help setting that up or getting past this particular issue, let me know and I'd be glad to lend a hand. I'll close this issue for now, but open another if you find anything else!
