### ISSUE TITLE
Cannot start up my applciation Error when login in

### ISSUE THREAD

**Issue by kevinwaxi** [austintoddj/canvas#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Call to undefined method Canvas\Models\User::authentications() - The main error that i am getting.
Currently, i am using laravel sail/docker with laravel 9. Users seemed to be seeded but I can not get past this error

**Comment by austintoddj** [comment]
Could you add a stack trace?

**Comment by jbenavidesv87** [comment]
I can help with this one:
`Warning: 1265 Data truncated for column 'user_id' at row 1 (SQL: update 'sessions' set 'payload'`

**Comment by austintoddj** [comment]
Marked as a duplicate of #851
