### ISSUE TITLE
Can't create posts

### ISSUE THREAD

**Issue by GazTheDev** [austintoddj/canvas#1046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have published to my Cloudways Host https://garethdaviesmedia.tech and have noticed once I've logged in I'm unable to create posts. It instead redirects to the posts page instead of allowing me to create a new post?. 

### Expected Behavior

Being able to post without re direction

### Environment

```markdown
PHP 8 
Laravel 9
MariaDB
```

**Comment by austintoddj** [comment]
@GazTheDev What role is assigned to the user in the `canvas_users` table?

**Comment by GazTheDev** [comment]
Hi @austintoddj  

On my DB it's "3" as the ADMIN and Role "2" as the user I created to check it. Everything else works expect the "create" posts page. Kind of strange. :(.

**Comment by austintoddj** [comment]
> it's "3" as the ADMIN and Role "2" as the user I created to check it

So as an Admin, you're not able to create a post?

Are there any errors in the console?

**Comment by austintoddj** [comment]
Closing as it needs more info.
