### ISSUE TITLE
Route [canvas.login] not defined.

### ISSUE THREAD

**Issue by kevinwaxi** [austintoddj/canvas#1065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have successfully created users in my production server, but when I try installing the application, I find that I cannot log in, which gives me an error of 500. Upon debugging this is the current error that I am facing

Route [canvas.login] not defined.

### Environment

```markdown
php version :8.0.8
laravel Version: 9.13.0
```

### Anything else?

I have hosted the application in shared hosting. Could this affect it? or is there a manual way to install this?

**Comment by austintoddj** [comment]
Are you defining custom paths in the .env file?

**Comment by austintoddj** [comment]
And just to make sure we're on the same page, you ran through the installation per the Readme?

In your Laravel installation, can you run `php artisan route:list` and see Canvas' routes defined?

**Comment by kevinwaxi** [comment]
tried reinstalling Canvas on the live server now doesn't install. Is there another way to install this?

**Comment by kevinwaxi** [comment]
The issue is resolved after a long day. Forgot to mention this but Awesome package.

**Comment by austintoddj** [comment]
Thanks for the kind words @kevinwaxi 😄
