### ISSUE TITLE
When visit /canvas-ui the js and css file can not find

### ISSUE THREAD

**Issue by caojianfei** [austintoddj/canvas#1086]
### Discussed in https://github.com/austintoddj/canvas/discussions/1085

<div type='discussions-op-text'>

<sup>Originally posted by **caojianfei** June 30, 2022</sup>
It looks like this:
![微信截图_20220630205409](https://user-images.githubusercontent.com/17742555/176682567-ec952fa3-7825-4af0-89fa-87005ca81e4f.png)

I have already run `npm run dev`:
![微信截图_20220630174628](https://user-images.githubusercontent.com/17742555/176682812-f1e5efbd-8881-4c96-b20a-746df486d11a.png)
</div>

**Comment by caojianfei** [comment]
When use laravel 8, there is no problem. I think mybe is is not support laravel 9(laravel 9.19) yet.

**Comment by austintoddj** [comment]
With the [recent move to Vite](https://twitter.com/taylorotwell/status/1541795873838989314) for bundling assets, it does look like a breaking change for anyone not on Mix anymore. I'll take a closer look and see if there's a relatively easy path forward.

**Comment by Charlesllamas** [comment]
You can follow the steps on section migrating-from-vite-to-laravel-mix
https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md#migrating-from-vite-to-laravel-mix

**Comment by austintoddj** [comment]
@caojianfei Did the above suggestion help you get your issue resolved?
