### ISSUE TITLE
[Feature] How can we integrate it in existing L5 instance?

### ISSUE THREAD

**Issue by Modelizer** [austintoddj/Canvas#11]
Is there a way to integrate canvas in existing L5 instance? If yes then please help me out.

**Comment by austintoddj** [comment]
In its current state, Canvas cannot be pulled into an existing Laravel installation. It's a standalone application. There have been quite a few requests for this to be available purely as a package that can be added to existing installations, so you may see this feature in an upcoming release. Thanks for checking out Canvas and stay tuned!

**Comment by Modelizer** [comment]
No problem... @austintoddj Thanks a lot for creating canvas... If possible il try to contribute... 👍
