### ISSUE TITLE
Maintenance Mode should whitelist admin users

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#111]
As of right now, if you visit `admin/tools` and put the site in Maintenance Mode, a user who is logged in will still be able to access anything in the admin section. Basically, user authentication is what enables the 'bypass' of admins in maintenance mode. 

The admin *should* be able however to look at the front-end of the blog as well, and not just the `admin/*` sections. I was thinking this could be done by creating a special token that would pass from the admin section to the view if an admin is previewing something, or perhaps just grab the IP of the admin user and let that be whitelisted against the maintenance mode.

Either way, the majority of this logic is kept in the custom middleware `app/Http/MiddlewareCheckForMaintenanceMode.php`

@nticaric I saw something on [tnt.studio/blog](http://tnt.studio/blog/maintenance-mode-and-whitelists-in-laravel-4) that made me think you may have some insight into this. Any help would be greatly appreciated!

**Comment by nticaric** [comment]
@austintoddj let me take a look and see what I can do
