### ISSUE TITLE
Protecting Admin Tools Routes

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#112]
If a logged-in user puts this in the url bar `admin/tools/reset_index`, the application will respond to it and run that portion. I'd like to see a way that we can protect routes like this, so a user could **ONLY** run the index reset by clicking the button on the tools page. Same goes for deleting a file etc. and other tool options. It's not a huge security risk, since the author of the blog isn't really meaning any harm to their own site, but the protection regardless would be nice to have.

**Comment by nticaric** [comment]
Am I correct if I say that the system doesn't have any roles and basically every user that is logged in is an admin?

If so, we should only change the request method to POST instead of GET so that the user cannot accidentally access it via url and reset the index

**Comment by austintoddj** [comment]
Yes you're correct. No users in the backend except the admin/author.
