### ISSUE TITLE
Using existing User model

### ISSUE THREAD

**Issue by dgillier** [austintoddj/canvas#1132]
### Is your feature request related to a problem? Please describe.

Unless you are creating just a blog, most other use are about adding a blog to an existing app.
And in this situation, there is already a User model and duplicating it make things more difficult...

### Describe the solution you'd like

I looked at your User table and there is just a few more fields but nothing used intensively...

I suggest to add some metadata to the existing User model by using, for example,  a package like https://github.com/99codes/laravel-meta-attributes...

### Validations

- [X] Follow our [Code of Conduct](https://github.com/austintoddj/canvas/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/austintoddj/canvas/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by PaulChase** [comment]
I totally agree.

The new canvas users table is not necessary, it could have just been merged with the existing users table.

**Comment by austintoddj** [comment]
It used to be that way. There's a [discussion](https://github.com/austintoddj/canvas/discussions/959) and [a related issue](https://github.com/austintoddj/canvas/issues/939) that dive a little deeper into it.

**Comment by austintoddj** [comment]
Closing this because I believe a separation is applicable to a number of situations. While it isn't necessary in all cases, I'd like to keep it as is for the time being. Thanks @dgillier for offering the suggestion though!
