### ISSUE TITLE
Publishing of posts not working

### ISSUE THREAD

**Issue by PaulChase** [austintoddj/canvas#1135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just installed the package and wrote a dummy post.

I clicked published and then clicked published now instead of scheduling.

But when I go to the posts page I can't find any published posts, but it appears in drafts.

I tried publishing it again but it doesn't work.

**Comment by austintoddj** [comment]
@PaulChase Can you verify that the timestamp in the database is sometime in the past?

**Comment by PaulChase** [comment]
> @PaulChase Can you verify that the timestamp in the database is sometime in the past?

The published_at column has a timestamp but yet the posts are showing as published posts

![image](https://user-images.githubusercontent.com/81924071/190659970-7c8bf3e5-6523-4ec8-b83b-466f370a3c39.png)

**Comment by PaulChase** [comment]
Okay I don't understand what is going on here, the posts I published last night are now showing as published after about 24hrs.

I then wrote another dummny post to test it out.
After I pubished it, it is still showing as draft in the 'canvas/posts' page.

Is there some kind of delay before a post shows as published?

**Comment by PaulChase** [comment]
It seems I've figured it out, It was difference in timezone that was the issue since canvas uses the laravel default timezone.

I just changed it to match my timezone (west african time).

**Comment by PaulChase** [comment]
It seems I've figured it out, It was difference in timezone that was the issue since canvas uses the laravel default timezone.

I just changed it to match my timezone (west african time).
