### ISSUE TITLE
Post not showing under published section, but is published.

### ISSUE THREAD

**Issue by noahdigesu** [austintoddj/canvas#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot from 2022-10-26 20-15-55](https://user-images.githubusercontent.com/62944748/198104604-01bf39e4-26bc-465b-bda0-ad33b2ef60c6.png)
![Screenshot from 2022-10-26 20-17-43](https://user-images.githubusercontent.com/62944748/198104928-580d1d02-17dd-497f-9375-7afdfe4284a3.png)

Even though the post is published (see pictures above), it shows up under the “draft” category.

Note : I have already changed my timezone to the correct one (ECT).

### Expected Behavior

Post should be shown under the "published" section.

### Steps To Reproduce

1. Have a fresh Laravel install
2. Install canvas without the Vite part / without Unsplash
3. Log in with the default user
4. Create a new post
5. Hit publish with the current date & time
6. Check that the post is shown as published in the top left corner of the editor
7. Check the `canvas/posts` route to see posts
8. Notice the post is still shown under “draft”, even though it is marked as published.

### Environment

```markdown
- PHP Version : 8.1.2
- Laravel Version : 9.37.0
- Database driver & version : sqlite 1.7.0
```

**Comment by noahdigesu** [comment]
Thanks in advance for the help !! 🤠

**Comment by austintoddj** [comment]
@noahdigesu I wasn't able to reproduce this on my end. Are you still stuck with this issue?

**Comment by noahdigesu** [comment]
Very confusing - did a new install, and it now works... Oh well, I guess it's better like that ahah
