### ISSUE TITLE
Change the canvas-ui page title

### ISSUE THREAD

**Issue by noahdigesu** [austintoddj/canvas#1158]
Hey :)

I was wondering if there is any way to change the page title of the `canvas-ui` front-end.
It says "Canvas" and I would like it to change to Smoothey's blog 🥤 (see images below).

Current state :
![Screenshot from 2022-11-07 17-46-39](https://user-images.githubusercontent.com/62944748/200366881-3656a080-6dbb-4451-8860-572742850171.png)

What I would like the title to be :
![Screenshot from 2022-11-07 17-47-04](https://user-images.githubusercontent.com/62944748/200366896-0919f78f-b533-4195-a7cb-37206f36aa08.png)

The title gets overwritten by the `ui.blade.php` view inside `vendor/austintoddj/canvas/resources/views`. A simple fix might be to use the `APP_NAME` variable from the `.env` file instead of having it hard-coded.

Thanks in advance ! :)

**Comment by noahdigesu** [comment]
Scratch that - for anyone who wants to do the same thing, you can go under `resources/js/canvas-ui/views/All[Posts/Tags/Topics].vue` to assign a custom title :)

**Comment by austintoddj** [comment]
Glad you found your answer @noahdigesu.
