### ISSUE TITLE
Save full path of images with domain appended to it

### ISSUE THREAD

**Issue by Ochieng424** [austintoddj/canvas#1187]
Images uploaded on the editor are saved without the domain as below. Check src value
`<img alt=\"Nottingham forest celebrating a goal\" src=\"\/storage\/canvas\/images\/WhNta2YxAKYOf7KXuyxRxSl1Z4jg3bvVPvjhGJuz.jpg\">`

How can I make the image src be saved with the full path eg: https://domain.com/storage/canvas/images/WhNta2YxAKYOf7KXuyxRxSl1Z4jg3bvVPvjhGJuz.jpg

**Comment by Ochieng424** [comment]
I have made a RESTful endpoint for posts and I would like to consume it on an android app. Without the full URL, images won't show

**Comment by austintoddj** [comment]
Thanks for the feature request @Ochieng424.

I don't have plans for building this into the current major version of Canvas, but I can get this into v7.0.

**Comment by austintoddj** [comment]
>I have made a RESTful endpoint for posts and I would like to consume it on an android app. Without the full URL, images won't show

I didn't quite catch the gist of the comment made here. If you've made a RESTful endpoint, why not just use [Laravel's `url()` helper](https://laravel.com/docs/10.x/helpers#method-url) when you're gathering the data you intend to return?
