### ISSUE TITLE
Share Article to Social Media Facebook, Linkedin etc

### ISSUE THREAD

**Issue by mdrdani** [austintoddj/canvas#1188]
Why do articles that have been published and shared on Facebook or Twitter don't see a thumbnail image or title? like medium or wordpress.

![Screenshot_21](https://user-images.githubusercontent.com/45899199/209139640-d4f5a995-6598-489b-98dd-b3e9c9890ea7.jpg)

**Comment by austintoddj** [comment]
Do the pages that you're trying to share have the proper meta data defined in the head element?

**Comment by austintoddj** [comment]
Are you using [Canvas UI](https://github.com/austintoddj/canvas#canvas-ui) or using your own template?

**Comment by mdrdani** [comment]
using Canvas UI sir, Laravel 8.

**Comment by mdrdani** [comment]
and one more thing if the article that we have published we convert it to draft, in the front view of canvas-ui if the tags or topic section of the article is still visible it should not be visible because it has already been drafted.

**Comment by austintoddj** [comment]
Looks like the same issue as https://github.com/austintoddj/canvas/issues/1187

As for the draft still being visible, it might be a timezone issue. Can you verify that the post you don't want visible has a `published_at` date in the future?

**Comment by mdrdani** [comment]
timezone set Asia/Jakarta. This problem is not urgent, but the urgent issue that I have made is why the thumbnail image or title on Facebook or Twitter doesn't appear.

**Comment by austintoddj** [comment]
I believe I've found the issue. In your `ShowPost` component that's in _resources/js/canvas-ui_, update your `metaInfo()` definition:

```js
// From this
{ property: 'og:title', content: this.post?.meta?.title || null },
{ property: 'og:image', content: this.post?.featured_image || null },
{ property: 'og:description', content: this.post?.meta?.description || null },

// To this
{ name: 'og:title', content: this.post?.meta?.title || null },
{ name: 'og:image', content: this.post?.featured_image || null },
{ name: 'og:description', content: this.post?.meta?.description || null },
```

Re-compile the assets and try scraping the URL again.

**Comment by mdrdani** [comment]
its same
![Screenshot_5](https://user-images.githubusercontent.com/45899199/210124794-a36c0a0d-3f1a-4d1c-8e00-45e6c49ff1b5.jpg)
![Screenshot_45](https://user-images.githubusercontent.com/45899199/210124803-97d75b39-c579-43b8-af4d-a09e5815bdd7.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/45899199/210124805-5fd402fd-0e3d-45cf-b970-a97d757b7886.jpg)

**Comment by austintoddj** [comment]
I tried scraping [this URL](https://mdrdani.my.id/canvas-ui/posts/terraform-beginner-part-2) myself on Facebook and Twitter. Neither render works - and Facebook actually gives a bit more info on the raw data that was scraped:

```html
<!DOCTYPE html>
<html lang="id">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="csrf-token" content="pDDF5yPTfxlMHhzYA0fByQnXELnpsALEqBlwHD2V">

    <title>Blog</title>

    <link rel="stylesheet" type="text/css" href="/css/canvas-ui.css">
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="//fonts.googleapis.com/css2?family=Karla&amp;family=Merriweather:wght@400;700&amp;display=swap">

    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/github.min.css">
</head>
<body class="mb-5">

<div id="ui">
    <router-view></router-view>
</div>

<script>
    window.CanvasUI = {"canvasPath":"canvas","user":null,"timezone":"Asia\/Jakarta"};
</script>

<script type="text/javascript" src="/js/canvas-ui.js"></script>
</body>
</html>
```

The Vue app isn't being resolved by the time the scrape finishes, so no metadata is found.

**Comment by mdrdani** [comment]
So, what should I do?
