### ISSUE TITLE
Link to GitHub page in "Edit Profile" page uses the configured Facebook username

### ISSUE THREAD

**Issue by dechristopher** [austintoddj/Canvas#12]
The link to the user's GitHub profile in the left column of the "Edit Profile" page in the admin dashboard uses the username that is configured for Facebook. Facebook itself uses the correct username, but the GitHub uses the configured Facebook username as well. 

This issue is local to the "Edit Profile" page from what I've seen. The frontpage of the blog generates and displays URLs properly as it should.

**Comment by austintoddj** [comment]
Thanks for the feedback! I'll get this fixed and pushed out in a day or so. Stay tuned!
