### ISSUE TITLE
how to deploy to vercel or netlify?

### ISSUE THREAD

**Issue by tanveerulhassan** [austintoddj/canvas#1205]
### Is your feature request related to a problem? Please describe.

how to deploy to vercel or netlify?

### Describe the solution you'd like

how to deploy to vercel or netlify?

### Describe alternatives you've considered

how to deploy to vercel or netlify?

### Additional context

how to deploy to vercel or netlify?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/austintoddj/canvas/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/austintoddj/canvas/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by austintoddj** [comment]
Take a look at this [tutorial by Caleb Porzio](https://calebporzio.com/easy-free-serverless-laravel-with-vercel).
