### ISSUE TITLE
how to use spatie pkg https://github.com/spatie/laravel-export with canvas for static site

### ISSUE THREAD

**Issue by tanveerulhassan** [austintoddj/canvas#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

how to use spatie pkg https://github.com/spatie/laravel-export with canvas for static site

### Expected Behavior

how to use spatie pkg https://github.com/spatie/laravel-export with canvas for static site

### Steps To Reproduce

how to use spatie pkg https://github.com/spatie/laravel-export with canvas for static site

### Environment

```markdown
how to use spatie pkg https://github.com/spatie/laravel-export with canvas for static site
```

### Anything else?

how to use spatie pkg https://github.com/spatie/laravel-export with canvas for static site

**Comment by tanveerulhassan** [comment]
![image](https://user-images.githubusercontent.com/53822107/214224605-677828d1-2697-4c4a-a62d-db12cc781cb9.png)
FACING THIS ISSUE

**Comment by austintoddj** [comment]
I'm not sure why you're getting permissions issue. Since this isn't a bug with Canvas, I'm going to close this out.
