### ISSUE TITLE
Profile Birthday field should be a date select

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#122]
Just like on the Post create/edit page where the field for `published at` is a date/time select, the profile birthday should not be just a text input, but instead a select like the post page.

**Comment by austintoddj** [comment]
@fergthh After merging the PR, I saw 1 issue only. The difference between the posts date select and the profile date select is that when you finally click on the day you want, the posts date select will keep the modal open, so you can kinda see what you selected. In the profile, the select modal closes immediately and just feels kind of jarring. Is that something you could look at? 
<img width="331" alt="screen shot 2016-08-14 at 8 33 27 am" src="https://cloud.githubusercontent.com/assets/8037011/17649387/f9b54cc0-61f9-11e6-845e-36e223d70eac.png">

**Comment by fergthh** [comment]
Done @austintoddj :+1:

**Comment by austintoddj** [comment]
Awesome @fergthh! #javascriptNinja
