### ISSUE TITLE
How to remove /canvas-ui from url?

### ISSUE THREAD

**Issue by AsifMian** [austintoddj/canvas#1243]
If we want to expose the ui to root path then how we can do that properly what file I need to modify because change web.php causes issue _so that its accessible from base domain instead of /canvas-ui_?

Thanks

**Comment by austintoddj** [comment]
Hello @AsifMian! After you install Canvas UI with the `canvas:ui` Artisan command, you should have new routes populated in the routes/web.php file. From here, you can either update or remove the prefix.
