### ISSUE TITLE
Exception is thrown when trying to format a non existent Phone number

### ISSUE THREAD

**Issue by braydeejohnson** [austintoddj/Canvas#13]
If you edit your profile and fail to enter a phone number, you get a ErrorException thrown.

> ErrorException in User.php line 49:
> Undefined offset: 1

The phone field should either be required, or some checking should be put in place to prevent exceptions on a null value.

I'll submit a PR.

**Comment by braydeejohnson** [comment]
Looks like this was resolved in ef6c7a6, should have looked there before creating this. :)

**Comment by austintoddj** [comment]
Thanks for checking it out! I Look forward to any more input you have on Canvas!
