### ISSUE TITLE
Undefined index : APP_TIMEZONE

### ISSUE THREAD

**Issue by soywod** [austintoddj/canvas#132]
First of all, you made a nice work here ! I've just downloaded it and I wanna use it for my portfolio / blog.

I have an error when visiting the `/admin/tools` route : **Undefined index APP_TIMEZONE** on `ToolsController` line 37 : `'timezone' => $_SERVER['APP_TIMEZONE']`. Indeed, the key `APP_TIMEZONE` is not in my `$_SERVER`.  But it is in the .env, so should not be `env('APP_TIMEZONE')` instead ? I tried with it and it works well

**Comment by austintoddj** [comment]
Thanks for the catch @soywod! Anything else you find that needs attention please let me know!
