### ISSUE TITLE
is it possible to add new page/module like posts and tags module?

### ISSUE THREAD

**Issue by hipe01mark** [austintoddj/canvas#1320]
I'd like to add a new page/module for customer invoices. Is it possible to create new routes and use canvas middleware to determine whether or not a user is logged in on canvas? Thank you in advance!

**Comment by austintoddj** [comment]
Hi @hipe01mark - you can use the `Authenticate` middleware in the same way that it's [being used here](https://github.com/austintoddj/canvas/blob/master/routes/web.php#L24).

As far as adding new pages/modules, you can add whatever you like to the base Laravel project you're developing in and then apply the middleware to your routes. Hope this helps.
