### ISSUE TITLE
Ability to create Page

### ISSUE THREAD

**Issue by msamgan** [austintoddj/canvas#1325]
### Is your feature request related to a problem? Please describe.

The majority of developers like to have pages on there blogs like About, Uses, etc. We need pages in canvas.

### Describe the solution you'd like

Ability to create page.

### Describe alternatives you've considered

NA

### Validations

- [X] Follow our [Code of Conduct](https://github.com/austintoddj/canvas/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/austintoddj/canvas/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by austintoddj** [comment]
Hi @msamgan - While Canvas does the heavy-lifting of blogs & publications in the backend, it's de-coupled from how you choose to display things on the frontend. I don't disagree that most developers would find use with the pages you mentioned. Canvas does provide [a basic frontend](https://github.com/austintoddj/canvas#canvas-ui) interface with the `canvas:ui` Artisan command, so any changes you'd like to see should likely go there. I'd be more than happy to take a look at a pull request if you create one.

**Comment by msamgan** [comment]
Hi Austin,

I am working on the PR for this feature.
can you please tell me what your preference is?
**Approach one:** 
- Adding a new table "canvas_pages" 
Pros: 
- everything is separated, there will be no conflict between posts and pages for future updates
Cons
- duplication in code for posts and pages
- complexity if the same code is used for both.

**Approach two:** 
Adding a new column "type" enum ("post", "page") with default "post" in the canvas_posts table (WordPress approach).
Pros: 
- fast to implement
- not much change in creation and edit 
Cons
- future updates for posts will be complicated.
- all posts APIs will be needing an update

please let me know, what is your verdict on this.
