### ISSUE TITLE
Laravel 5.3 Upgrade

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#133]
Just created a branch for upgrading Canvas to Laravel 5.3! My daughter was just born a few hours ago, so I don't have a ton of time to tackle this at the moment, but wanted to open it up and see if any of you wanted to upgrade Canvas to 5.3. Looks like the [upgrade guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) is pretty complete, hope someone feels like tackling this so we can continue on with developing new features! 

**UDPATE**:  Used [Laravel Shift](https://laravelshift.com) as a service to upgrade Canvas to Laravel 5.3. A new branch was created named `laravel-5.3-shift` with pretty comprehensive notes on what worked and what didn't work with the upgrade. I'd say 80% of the work is done, only needing a few more tweaks before we can push this live. 

If anyone would like to lend a hand and take a stab at finalizing that branch to pass all it's tests, I'd be super grateful! 

@erikgall @nticaric @fergthh @talvbansal @RDelorier @naneri @foxted

**Comment by fergthh** [comment]
Congratulations @austintoddj! A new programmer to the world? :baby_bottle: 

I'll see if this weekend will cast an eye to the update. I think it's a good time to complete the pending tests.

Congratulations again and happy life!

**Comment by austintoddj** [comment]
Thanks @fergthh! Can't wait to see what she'll be when she grows up. Looking forward to some more Canvas magic you always put together!

**Comment by soywod** [comment]
Congrats  @austintoddj :)

**Comment by talvbansal** [comment]
Ahh congrats @austintoddj :balloon: :tada:

**Comment by erikgall** [comment]
Congrats @austintoddj. If I have time, I'll see what I can do.

**Comment by foxted** [comment]
Congrats @austintoddj !!

**Comment by austintoddj** [comment]
Thanks so much guys, it's really nice to know this app can get some love when I'm busy holding the baby through the long hours of the night. :)

**Comment by nticaric** [comment]
Congrats @austintoddj, we all are so happy for you!

**Comment by austintoddj** [comment]
@foxted So I merged the 5.3 branch into master just now, just to make sure the HEAD didn't get too far away from us. If you're still able to make those changes we discussed earlier, that'd be awesome. Let me know what you think!

**Comment by RDelorier** [comment]
A little late to the celebration but congratulations to you and your wife!!!
