### ISSUE TITLE
[Suggestion] Add CV

### ISSUE THREAD

**Issue by soywod** [austintoddj/canvas#138]
What about adding its own CV, and why not adding a picto next to the blog name or socials to download it in PDF ?  I've just added it on my blog [http://soywod.fr](https://soywod.fr), let me know if this could interest you, and I'll make a pull request

**Comment by austintoddj** [comment]
Great idea @soywod! Love your blog and how you personalized it. If you want to make a PR to implement this as a new feature, I'll gladly pull it in!

**Comment by soywod** [comment]
I'm glad to contribute to your awesome project :)
