### ISSUE TITLE
Customized Email Blade Template

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#157]
If anyone has more clarification on this issue that'd be awesome.

I know in previous versions of Laravel, you can customize email templates from the default HTML that is sent, for something like password resets. Laravel 5.3 takes it a step further and generates some nice templates for you. My question is, if we wanted to make a custom blade template for the password reset notification, how would we go about doing that?

**Comment by foxted** [comment]
You could try something like this: https://laravel.com/docs/5.3/notifications#customizing-the-template

**Comment by austintoddj** [comment]
Thanks for the link @foxted! Checking it out now.
