### ISSUE TITLE
Unexpected character when running artisan during first setup

### ISSUE THREAD

**Issue by Vviizard** [austintoddj/canvas#169]
I downloaded canvas today to try it out. I have followed the instructions within the readme, but I've run into an issue at Step 5. When I run `php artisan canvas:install`, I recieve the following error:
```
<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>[path]/Canvas-Blog/artisan</b> on line <b>31</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>[path]/Canvas-Blog/artisan</b> on line <b>31</b><br />
```
The PHP version is set to 5.6 and I am hosting it on a webspace.
I have made sure that the `.env` is filled out correctly, that composer downloaded everythign and that `public/uploads/` and `storage/` have the `777` permission level.
Also, a link to the site as it currently is: [Blog](http://canvas.vviizard.eu)

I hope this is enough information, this is the first time I am reporting an issue like this.

**Comment by Vviizard** [comment]
It seems that my hosting provider is simply lying when saying that PHP 5.6 is enabled, the highest php-cli I can get seems to be 5.5.38. Case closed.

**Comment by austintoddj** [comment]
Thanks for checking out Canvas @Vviizard! Sorry to hear about the bug you ran into, but glad you got it sorted out. Let me know if there is anything else you need assistance with!

**Comment by Vviizard** [comment]
It'd help if you could send me pre-configured sql.zip exports so I can import it to my database. That'd get me around the inability to run the installation. Or does the artisan command do anything else, apart from setting up the DB?

**Comment by austintoddj** [comment]
@Vviizard The install command sets a few blog options, Title, Subtitle, Author, and more settings. It also runs the initial search index, which can be done from the GUI once installed. So, I can sure send you a `.sql` dump of the database for starting out. Is `hello@vviizard.eu` the best email to reach you at?

**Comment by Vviizard** [comment]
Yes. Thanks!
