### ISSUE TITLE
Add Twitter Cards

### ISSUE THREAD

**Issue by Vviizard** [austintoddj/canvas#174]
I've started working on support for twitter cards.

- [x] Add meta-tags
- [x] Add setting: "Twitter Card Type". Globally sets twitter card type for the blog.
- [x] Add new database entry. (Table: `settings`, `setting_name: twitter_card_type`, Type: String, Possible Values: `summary`, `summary_image_large` or ` ` (If empty or invalid, Twitter will not add a card))
- [x] Add tests

Why: Twitter cards reportedly increase interaction with posted links and it's a neat feature to have.
Additional Resources: [Twitter Card Validator](https://cards-dev.twitter.com/validator), [Twitter Card Doucumentation](https://dev.twitter.com/cards/getting-started)

**Comment by Vviizard** [comment]
@austintoddj Current progress: https://github.com/Vviizard/canvas/commit/1fd389f4620f9e0748ab366622cb1012481c5e44

**Comment by austintoddj** [comment]
@Vviizard Thanks for doing this, it's something that I wanted to put in the application a long time ago, but never got around to doing it. Good checklist as well. Look forward to merging this in as soon as possible!

**Comment by Vviizard** [comment]
Added Menu options: https://github.com/Vviizard/canvas/commit/aa0b80412cf67e32f366bf47073cc29c83ae9a15
@austintoddj I may require some assistance with tests later, because I haven't worked with them yet.

**Comment by Vviizard** [comment]
@austintoddj Should I close this now, or after #178 has been pulled?

**Comment by austintoddj** [comment]
Sorry @Vviizard haven't got to take a look at it yet. I'll close this one out as soon as I pull #178. Getting macOS Sierra up and running on a clean install, then Valet, then this. 👍
