### ISSUE TITLE
jQuery Author Popup Overlay

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#179]
On each blog post page, there is an author signature at the bottom, specifying some personal social media channels, the author name and the author bio.

To give a little more information, including the ability to have a contact link, and downloadable Resume/CV link(If the author included this), I'd like to see a popup implemented by clicking on the Author name or gravatar.

Take a look at this [working example](http://dev.vast.com/jquery-popup-overlay/), specifically the `Stand Alone` button.

I've created the `author-popup` branch as a starting point, and anyone who wants to take a stab at this is more than welcome! 

Contributors who I thought may be interested or have shown skill in this area:
@talvbansal  @fergthh @Vviizard @soywod

**Comment by austintoddj** [comment]
@fergthh Here is an issue I opened regarding what we chatted about a little while ago.

**Comment by austintoddj** [comment]
@Vviizard Any interest in trying to tackle this?

**Comment by Vviizard** [comment]
@austintoddj I'll try some stuff tomorrow.
What do you think of using the standalone-type and putting a link-button in the footer that says imprint? That would tackle https://github.com/austintoddj/canvas/issues/142#issuecomment-248007136

**Comment by austintoddj** [comment]
@Vviizard I'm not opposed to having this. I do like the ideas presented in #177 though, if we could figure out a way to extend Canvas via plugins, that way the other users who are not restricted by this law won't have to include it in their blogs. Does that make sense?

**Comment by Vviizard** [comment]
@austintoddj #142 was a suggestion to add a contact-me-page. An imprint satisfies the needs of the contact-page, and calling it `imprint` instead of `about` or `contact`, satisfies the law and is still understandable.

**Comment by austintoddj** [comment]
@Vviizard The contact page was supposed to turn into the author popup. So instead of having another entire page, just having any contact info, author info, resume to download, was all supposed to comprise the standalone popup. 

Another thought is this: What if you had an Impressum document, could upload it from the admin, and just like the Download Resume/CV, it could show up in the author popup?

**Comment by Vviizard** [comment]
@austintoddj Currently running into an issue with the scroll-to-top button. It causes a weird interaction with jquery.popupoverlay. I think it's because every page with a scroll-to-top button has two head/body elements.

**Comment by Vviizard** [comment]
@austintoddj Because there are two body elements, it puts the overlay in both.

**Comment by austintoddj** [comment]
@Vviizard Thanks for catching that. I know @fergthh put the Scroll to Top feature together in #147, maybe there is something we can tweak there?

**Comment by Vviizard** [comment]
@austintoddj I'm not sure, I've commented it out for the time being.

**Comment by Vviizard** [comment]
@austintoddj I've got an example running: http://blog.vviizard.eu

**Comment by austintoddj** [comment]
@Vviizard Really like that. Looks good. The only 3 thoughts I have about this are:

1. Not everyone will require this. So to make it a default in the footer seems unnecessary. Letting it be an option that can be edited or taken care of from the admin section makes more sense.
2. Getting the Back to Top button back in is important
3. Can you apply this functionality to the author name/gravatar and have the popup display the author details?

**Comment by Vviizard** [comment]
@austintoddj 
1 - I've not touched backend yet, I'll look at it tomorrow
2 - The frontend.js code must be changed
3 - Check it out now: http://blog.vviizard.eu

**Comment by austintoddj** [comment]
@Vviizard Yup, that's about what we're going for.

**Comment by talvbansal** [comment]
The current scroll to top implementation  is overkill from what I can see, ill send a pr with a much simpler one on Sunday

**Comment by austintoddj** [comment]
You're the man @talvbansal

**Comment by talvbansal** [comment]
You can take a look at my attempt at this, i have a branch called `vue` which adds a similar set of functionality without adding a new library dependency outside of the libraries laravel ships with.

**Comment by austintoddj** [comment]
Alright, super n00b question here. How can I check out your `vue` branch?

**Comment by talvbansal** [comment]
@austintoddj  I just created a PR for you
