### ISSUE TITLE
Drafts can still be seen

### ISSUE THREAD

**Issue by izdiwho** [austintoddj/canvas#185]
Not sure if it's an issue, but somehow drafts can still be accessed. I know it's probably because of the preview feature, but I thought that by default drafted posts aren't supposed to be accessible?

**Comment by austintoddj** [comment]
Good catch @izdiwho. Never actually tried accessing drafted posts, but you're correct, the preview feature would be the loophole. 

Can you think of any good ways to protect those pages other than passing through some session token?

**Comment by izdiwho** [comment]
I think @jlaswel's PR got it right.

**Comment by austintoddj** [comment]
@izdiwho Thanks for your help on this! Didn't even realize this was possible until you brought it up, and now I'll merge in the fix as soon as @jlsawell makes one last tweak.  👍
