### ISSUE TITLE
The markdown parser is not interpreting images with spaces in the path

### ISSUE THREAD

**Issue by talvbansal** [austintoddj/canvas#187]
If you upload an image with space in the path name at any point (folder or filename), the file will upload correctly. SimpleMDE's internal Javascript engine will parse the file correctly and render it within the preview window however when saving a post the PHP parser doesn't identify it and just renders the markdown as plain text.

Spaces in paths are not ideal but many people will use them so we should agree on a way to handle this. 

The easiest would be to strip / replace spaces with hyphens or underscores at the point of upload via the media-manager. However this is not strictly a media-manager issue but one with the PHP parser being used.

**Comment by austintoddj** [comment]
@talvbansal Good catch, never ran into this before. So you're saying it's something that [Parsedown](http://parsedown.org/) is doing? I do like your idea of stripping/replacing the spaces, I'm open to your best judgement on it.

**Comment by talvbansal** [comment]
I just had an idea whilst out on lunch for the media manager to replace spaces with `%20` which seems to fix the issue - url encoding the paths doesn't work as it converts slashes as well but a simple `str_replace` has done the trick! 

Will update the media-manager now and submit a PR for it asap!

**Comment by austintoddj** [comment]
Lunch is the best time for solutions to pop up! Will merge in the PR as soon as it comes in.

**Comment by talvbansal** [comment]
Fixed!

Nothing to change on the Canvas side just a `composer update` to bring the latest media-browser in.

Since you're ignoring the `composer.lock` file and the `media-manager` version is set to `1.0.*` there's actually nothing more to do here :)
