### ISSUE TITLE
Media Manager Tests

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#188]
The Media (Uploads) portion of Canvas got a huge update lately, and is now operating as a VueJS component. There are no tests written for the functionality of uploading files/creating folders/deleting etc. with this new feature.

If anyone out there has a good handle on testing something like this, please feel free to submit a PR!

Contributors who I thought may be interested or have shown skill in this area:

@RDelorier @erikgall

**Comment by RDelorier** [comment]
Hey sorry I haven't gotten in there to look at the search tests yet I've
just been swamped lately but it's #1 on my open source list as soon as I
get a chance

**Comment by austintoddj** [comment]
@RDelorier No worries at all, just wanted to keep you included since you are a big part of Canvas' growth! 👍

**Comment by austintoddj** [comment]
After thinking about this for 5 minutes, testing this on our end won't be the most essential since [Media Manager](https://github.com/talvbansal/media-manager) has its own suite of tests and this is a JS package, meaning our PHP testing won't be able to accomplish much. Closing this out.
