### ISSUE TITLE
Add the current canvas version number or latest commit hash for the System info

### ISSUE THREAD

**Issue by talvbansal** [austintoddj/canvas#194]
Currently when using the information from the "System Info" panel to assist with debugging a users problems, we have no way of knowing if they're using the latest version of Canvas or not. 

I think it'd be good to be able to have that information for the user to submit along with the rest of the report just we can rule out if they're on an old version of the application or not.

I'm really not sure how to do this or if its possible so I'm just putting it out there for now.

**Comment by austintoddj** [comment]
@talvbansal I agree. I haven't figured out how we could persist that to the application. If we could save that to the database somehow, I could even use that info in another part of the application. Ideally, I'd like to keep the application version number and the theme name as settings in the database that get updated as needed.

Very open to suggestions on this.

**Comment by lszanto** [comment]
#197

**Comment by austintoddj** [comment]
Currently fixed with #197

**Comment by austintoddj** [comment]
@lszanto One last thing on this. For those who are using versions of Canvas older than 2.1.7, nothing will show up for the Settings value. Could we perhaps add a condition in the controller or the view that says if no value is present in the database, then it must be `Older than v2.1.7`? That way at least some value will be seen in the view.

**Comment by lszanto** [comment]
@austintoddj Sure thing, i'll add that in about an hour or so when I get home.
