### ISSUE TITLE
TNTSearch Laravel Scout Driver

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#195]
@nticaric 
Ran into a bug recently in which when I save/update a post or tag, the index is not running. It wasn't until I ran the console command `canvas:index` that it actually updated the index. So my question is, are we running the index correctly after any post/tag interaction on the site?

Here is what it looked like running the console command manually:
![screen shot 2016-09-30 at 6 31 52 am](https://cloud.githubusercontent.com/assets/8037011/18990626/d17ff1a2-86d8-11e6-9a6f-1a4af8d1515d.png)

**Comment by talvbansal** [comment]
If you move to Laravel Scout now that Canvas is using Laravel 5.3 I'm pretty confident that the indexes are automatically updated when a model is saved or generated

**Comment by nticaric** [comment]
@austintoddj as I can see the index should be updated on insert/update/delete if the environment is different than testing

https://github.com/austintoddj/canvas/blob/master/app/Models/Post.php#L183

but as @talvbansal mentioned, we should probably switch to Laravel scout with tntsearch driver

**Comment by austintoddj** [comment]
@nticaric Thanks for shooting that line number over. Would you want to look into using the [Laravel Scout TNTSearch Driver](https://github.com/teamtnt/laravel-scout-tntsearch-driver)? I'm all for using that if you'd want to implement it.

**Comment by talvbansal** [comment]
If you need any help let me know, I've implemented it in a project previously

**Comment by austintoddj** [comment]
@talvbansal If you want to take a stab at it, or if @nticaric doesn't have time, feel free! Either way works for me 👍

**Comment by nticaric** [comment]
@talvbansal you can go ahead on this one, I can join you later when I manage to find some spare time

**Comment by talvbansal** [comment]
@nticaric sorry I've been at a conference all weekend I'll take a stab at it later this evening!
