### ISSUE TITLE
Replace hardcoded version number

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#206]
Right now, the `at-a-glance.blade.php` file contains two hardcoded version values for Canvas. These values **SHOULD BE** the latest release of the project. As of right now, I could not find a way to dynamically grab those values specifically from GitHub's API. The API can be accessed at:

```php
https://api.github.com/repos/austintoddj/canvas/releases/latest
```

The `name` or `tag_name` values should be enough to replace the hardcoded values.

Hardcoded values begin at Line 36:
```php
@if($data['canvasVersion'] !== 'v2.1.7')
    <hr>
    <a href="{{ url('https://github.com/austintoddj/canvas/releases/tag/v2.1.7') }}" target="_blank"><small>Canvas <span id="tag_name"></span></a> is available! <a href="https://github.com/austintoddj/canvas/UPGRADE.md">Please update now.</a></small>
@endif
```

If anyone wants to take a stab at replacing those hardcoded values with the values accessed from the API, please feel free!

**Comment by tarlepp** [comment]
Hmm, what about ```composer.json``` https://getcomposer.org/doc/04-schema.md#version

**Comment by austintoddj** [comment]
Good thought @tarlepp. Looked at that while going through this process, but couldn't find a substantial enough solution for it. Do you know of a way?

**Comment by asmita005** [comment]
Hello,
I have used curl to get the latest version from the API. Its working fine. Should i do a pull request ?

**Comment by austintoddj** [comment]
@asmita005 Thanks for doing this! 

Yes, you can submit a pull request right away. The file is located at:

`resources/views/backend/home/sections/at-a-glance.blade.php`

**Comment by tarlepp** [comment]
I'm just thinking about scenario that API has newer version than user which uses this application. That is why I would use composer.json version content instead.

Although I have never done that, but it should not be that hard.
