### ISSUE TITLE
Date/Time picker highlight today

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/Canvas#21]
The highlight today portion of the datetime picker is just a tiny bit off, design-wise. Instead of the broken circle, it should be a full circle. 
<img width="288" alt="screen shot 2016-07-07 at 8 01 46 am" src="https://cloud.githubusercontent.com/assets/8037011/16654042/8bc3e3aa-4419-11e6-8c0a-d3a042ca8a12.png">

**Comment by austintoddj** [comment]
As a side note, the color of the picker should change to be the primary blue of the header bar.

Blue
#2196F3

**Comment by talv86** [comment]
PR submitted

**Comment by austintoddj** [comment]
Fixed with commit: 3eee320f48b749b489022b0653db07efdde81a42
