### ISSUE TITLE
[admin] Sorting posts by date not working properly

### ISSUE THREAD

**Issue by cconover** [austintoddj/canvas#215]
When sorting the list of posts by date in the admin interface, it does not appear to work as expected. It will sort them by month, but will then sort in chronological order within each month. What I would expect it to do is sort in direct chronological (or reverse chronological) order.

<img width="90" alt="screen shot 2016-10-09 at 11 52 21 am" src="https://cloud.githubusercontent.com/assets/698158/19221742/0928364c-8e17-11e6-9d05-dd63a0c87066.png">

<img width="97" alt="screen shot 2016-10-09 at 11 51 52 am" src="https://cloud.githubusercontent.com/assets/698158/19221743/0cfcdca0-8e17-11e6-937f-bf364417ec89.png">

**Comment by austintoddj** [comment]
@cconover This should be fixed now thanks to @vuchl, let us know if you run into any more issues with it!
