### ISSUE TITLE
Deleting a Post unit test

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#217]
With the recent re-factoring of the `admin/post/create` and `admin/post/create` pages, the `testPostsCanBeDeleted()` on line 146 of `PostTest.php` is consistently failing. The UI/UX of the actual GUI works like it should, and the application functions properly. The test however fails. If anyone would like to jump in here that'd be awesome!

Contributors who I thought may be interested or have shown skill in this area:
@RDelorier @erikgall

**Comment by lcrossan** [comment]
i got it, if this is up for grabs. you just want the test deleted?

**Comment by austintoddj** [comment]
@lcrossan Actually, we just need that test to actually work. Right now, the functionality is commented out. But take a look and see what you can do!

**Comment by RDelorier** [comment]
You could skip the ui interaction and just do send the delete request directly and assert its no longer in the database.

@austintoddj if you ever want to skip a test until it's fixed then there is a markedSkippedTest function that will just show the test as skipped when running phpunit.

**Comment by austintoddj** [comment]
@RDelorier @erikgall Thanks for helping out with this guys, you rock!
