### ISSUE TITLE
If there is no user with id=1, no content output 

### ISSUE THREAD

**Issue by yurakaras** [austintoddj/canvas#226]
While installing Canvas, i've got some issues, and in the result i got user with id <> 1

>  frontend/BlogController.php

```
public function index(Request $request)
    {
        $user = User::findOrFail(1); // if not 1 ?
```

Does Canvas support multi users ? 

If no, then probably firstOrFail() method is more appropriate.

I checked, it works.

**Comment by austintoddj** [comment]
@yurakaras Thanks for catching this.
