### ISSUE TITLE
SettingsController - Creating default object from empty value

### ISSUE THREAD

**Issue by edyrkaj** [austintoddj/canvas#228]
From the first run of application settings table is empty so this caused error
on saving modifications (Can't update first() object of nothing !) after accessed application.

**Comment by edyrkaj** [comment]
Please add this file to db/seeds/SettingsTableSeeder.php

`<?php

use App\Models\Settings;
use Illuminate\Database\Seeder;

/*
* This class used to fill content of database table settings with some default value
*/
class SettingsTableSeeder extends Seeder
{
    /**
     * Seed the settings default on first run
     */
    public function run()
    {
        $data = [
            'blog_title'=> 'Canvas',
            'blog_subtitle'=> 'Canvas',
            'blog_description'=> 'Canvas',
            'blog_seo'=> 'Canvas',
            'blog_author'=> 'Canvas',
            'disqus_name'=> '',
            'ga_id'=> '',
            'twitter_card_type'=> ''
        ];

        foreach ($data as $key => $value) {
            Settings::create(['settings_name' => $key, 'settings_value' => $value]);   
        }        
    }
}
`

**Comment by austintoddj** [comment]
@edyrkaj What value were you trying to modify in the application that caused an error to be thrown? I haven't run into the issue you're referring to before.

**Comment by edyrkaj** [comment]
When it does update of settings it refers to first object found in db. But when you don't have row it crashes and return error exception

**Comment by austintoddj** [comment]
There shouldn't be an empty row in the `settings` table if you've gone through the initial install of the application. The only way I could see this happening is if you're currently running an older version of Canvas where the settings table was not set up or pre-filled via the install command. Is that the case for you @edyrkaj?

**Comment by DesmondPang** [comment]
The store function in SettingsController  query the first but get null

` $blogTitle = Settings::where('setting_name', 'blog_title')->first();`

I think you should modify it the updateOrCreate(). 

Please replace all stuff in the store function to


`    public function store(SettingsUpdateRequest $request)
    {
      
      
        Settings::updateOrCreate(['setting_name' =>'blog_title'],['setting_value'=> $request->toArray()['blog_title']]);

        Settings::updateOrCreate(['setting_name' =>'blog_subtitle'],['setting_value'=> $request->toArray()['blog_subtitle']]);
        
        Settings::updateOrCreate(['setting_name' =>'blog_description'],['setting_value'=> $request->toArray()['blog_description']]);
        
        Settings::updateOrCreate(['setting_name' =>'blog_seo'],['setting_value'=> $request->toArray()['blog_seo']]);
        
        Settings::updateOrCreate(['setting_name' =>'blog_author'],['setting_value'=> $request->toArray()['blog_author']]);
        
        Settings::updateOrCreate(['setting_name' =>'disqus_name'],['setting_value'=> $request->toArray()['disqus_name']]);
        
        Settings::updateOrCreate(['setting_name' =>'ga_id'],['setting_value'=> $request->toArray()['ga_id']]);
        Settings::updateOrCreate(['setting_name' =>'twitter_card_type'],['setting_value'=> $request->toArray()['twitter_card_type']]);

        Session::set('_update-settings', trans('messages.save_settings_success'));

        return redirect('admin/settings');
    }`

**Comment by austintoddj** [comment]
@DesmondPang Thanks for the snippet of code. Merging it in now.
