### ISSUE TITLE
It takes so long for updating post.

### ISSUE THREAD

**Issue by ibnujakaria** [austintoddj/canvas#238]
I don't know what happens, but everytime i edit my post, the process just takes so so so long. More than 20s.

I run it on Arch Linux with PHP 7.0.12 Development Server. 

I have run the `./artisan optimize` and its still the same.

Any idea?

**Comment by ibnujakaria** [comment]
After trying to figure out what happens, i got some conclutions that the `ParseDowner::toHtml()` that slows down the process. The larger text i write, the longer its process takes. I wrote 1953 words and 372 lines and the result is really annoying.

**Comment by talvbansal** [comment]
Thats weird, I have an install running on a $5 Digital Ocean instance running Ubuntu 16.04 also hosting 4 other (very low volume traffic) sites, I've just run an update on an  article I've written which is 275 lines and 1955 words and it took 4 seconds to update.

**Comment by ibnujakaria** [comment]
I try it out with nginx web server and it reaches the maximum time executions.

**Comment by Naoray** [comment]
@ibnujakaria I am also using `nginx` on `Ubuntu 16.04` and it works fine!

**Comment by talvbansal** [comment]
@ibnujakaria I run nginx locally and apache2.4 on my DO host both have no problems, at this point I'd assume you have a config issue somewhere along the way.

**Comment by austintoddj** [comment]
@ibnujakaria Sorry to hear that you're having that issue. As the others have said above, it sounds perhaps like it's a config issue with the setup, as I've also tried Canvas on multiple servers and it seems consistent with it's speed. If possible, are you able to try Canvas locally on macOS or something else?

**Comment by ibnujakaria** [comment]
Thanks guys! I tried it on a shared host with apache2 and php7 and it works like a charm!

**Comment by austintoddj** [comment]
@ibnujakaria Glad you worked it out! Thanks for using Canvas!
