### ISSUE TITLE
404 does not get returned if logged in

### ISSUE THREAD

**Issue by Naoray** [austintoddj/canvas#240]
If you are logged in and go to some route, which does not exists it looks like this:
![image](https://cloud.githubusercontent.com/assets/10154100/19699717/b8999afa-9af4-11e6-953b-de5d5a4a0110.png)

I looked into `app/Exceptions/Handler.php` but this seems fine. I also did an `dd('test')` in `404.blade.php` and it gets displayed.

Anyone an idea why it is not showing up the error site?

**Comment by austintoddj** [comment]
@Naoray Yeah I've seen this before, so it's a known issue that I've never addressed. 

Not exactly sure why it's doing this. If you want to dig into it, I'd be really curious to know. But now that you brought it up, I'll try and give it a look in the next couple days as well.
