### ISSUE TITLE
Can't access Admin area

### ISSUE THREAD

**Issue by donmarkus** [austintoddj/canvas#248]
I got this error while trying to access admin area

`Method Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception, caught BadMethodCallException: Method [getFiles] does not exist.`

**Comment by talvbansal** [comment]
Hi @donmarkus, this is a know error when using laravel 5.3.21, the latest commits to Canvas hard code laravel 5.3.20 until a patch by Proengsoft can be pushed out.

It seems a few other packages have had breakages as a result of the 5.3.21 release [too](https://twitter.com/NicolasWidart/status/793035977505800192)

**Comment by austintoddj** [comment]
@donmarkus 

Like @talvbansal pointed out, Proengsoft is hopefully working on a solution. Until that time, we've released `v2.1.12` which will take care of the issue for now. Let us know if there is anything else we can help you with.

**Comment by austintoddj** [comment]
@donmarkus If this issue has been resolved for the time being, please close the issue. You are free to reopen another for anything else.

**Comment by dryyun** [comment]
I use release - v2.1.15 , also get the issue , is it fix ?
