### ISSUE TITLE
[Suggestion] Make canvas co-author usable

### ISSUE THREAD

**Issue by Naoray** [austintoddj/canvas#249]
Scenario: me and my friend want to start a blog where we both can write/edit/delete articles.

Problem: currently canvas is only designed to have one author. Means posts are not owned by an author, they are simply stored in the db.

I've just started to develop an `artisan` command, which registers a new user, but that won't be sufficient. We would need to implement an `owner` relationship from the `user` to `post` model. Anything else we have to include in this feature to make it work?

Is someone interested in this feature?

**Comment by Naoray** [comment]
Have started to work on this feature. As far as I can tell it is almost ready, there is just one issue I discovered so far:

When I try to create a post I get an exception:
![image](https://cloud.githubusercontent.com/assets/10154100/19926109/1d25213e-a0f3-11e6-9ebb-5eb383ba445f.png)

Could someone take a look at this error?

You can find the current code for this feature in the [coauthor](https://github.com/naoray/canvas/tree/coauthor) branch.

**Comment by talvbansal** [comment]
When I'm back in the UK early next week I can help look into this.

**Comment by talvbansal** [comment]
So i had a look into this, not sure what the solution is but its because of the way that TNTSearch is not handling the relationship created by the posts and user models. We'll need to explore this further maybe raise the issue on the TNTSearch page see if anyone there can recommend something?

**Comment by talvbansal** [comment]
So I have the fix for this but I'm not sure how to contribute it to your fork? If I try and fork your repo i just end up with my forked canvas repo, any ideas?

**Comment by Naoray** [comment]
@talvbansal maybe you have to add a new remote "link", like suggested [here](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Comment by talvbansal** [comment]
Just tried that but got : 
`remote: Permission to naoray/canvas.git denied to talvbansal.`

**Comment by talvbansal** [comment]
@Naoray thanks for the invite, just pushed my changes up, take a look see if you're happy with them

**Comment by Naoray** [comment]
@talvbansal thanks! That worked. #252

**Comment by austintoddj** [comment]
Added user management in `v2.1.13`.

https://github.com/austintoddj/canvas/releases/tag/v2.1.13
