### ISSUE TITLE
login background does not cover the whole page

### ISSUE THREAD

**Issue by Naoray** [austintoddj/canvas#258]
If I go to `/admin` in version 2.1.14 the login page looks like:

![image](https://cloud.githubusercontent.com/assets/10154100/20383185/133eef66-acaf-11e6-9251-1469218aed1c.png)

If I add a `class="clearfix"` to the `#main` element it looks like this:
![image](https://cloud.githubusercontent.com/assets/10154100/20383284/7479cb7a-acaf-11e6-9e51-75ddf4cacf77.png)

Also tried to adjust the `#main` and `body` height to 100%, but it didn't work.

@austintoddj just a quick thought: currently canvas uses bootstrap. Bootstrap still doesn't use `flexbox`, which is a really powerful feature. Have you considered changing to maybe [bulma](http://bulma.io/)?

**Comment by austintoddj** [comment]
Never looked at [Bulma](http://bulma.io) before. 

And the login page in fact was supposed to be like that, just the top portion containing the image. Was not necessarily happy with how it turned out though, so it'll be revisited soon.

**Comment by Naoray** [comment]
@austintoddj I just came across [Bulma](http://bulma.io) because of [Laracasts](www.laracasts.com)... in the `flexbox` - series it go mentioned...

**Comment by austintoddj** [comment]
Nice. I'll take a look at re-doing the login page in the near future, but if you're good with this issue you can close it out 👍
