### ISSUE TITLE
Installing via Packagist does not handle admin user as admin

### ISSUE THREAD

**Issue by Naoray** [austintoddj/canvas#259]
I've installed Canvas 2.1.14 via Packagist first, set everything up and logged in:
![image](https://cloud.githubusercontent.com/assets/10154100/20383971/3be0360c-acb2-11e6-893e-2cd5a6ce3836.png)

After realizing my current Admin user couldn't see nor access the `Usermanagement` tab, I installed canvas via cloning the repository, set it up like before... and everything worked.

![image](https://cloud.githubusercontent.com/assets/10154100/20384087/b8b4f992-acb2-11e6-96ee-4af63983bd6f.png)

I did check the resources in both projects, they seem equal... also the admin user database entry.

Thoughts?

**Comment by austintoddj** [comment]
@Naoray When you installed both times, did you start from a completely new database?

**Comment by Naoray** [comment]
Yes

**Comment by austintoddj** [comment]
@Naoray Ah ok, sounds like this may be the same issue as #255. I believe packagist is simply not pulling in the most recent commits to the project, which would explain your admin access issue and the previous version issue. I think drafting a new release would solve this. I'll look into this shortly.

**Comment by austintoddj** [comment]
@Naoray  Should be fixed now with `v2.1.15`.

**Comment by Naoray** [comment]
Tested it! => resolved
