### ISSUE TITLE
Replacement JSValidation

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#260]
So, because of #247 and the fact that Proengsoft is not responding to their broken package, I want to see if we can find a way to replace [Laravel JSValidation](https://github.com/proengsoft/laravel-jsvalidation) with an alternative validator, preferably one that is an active project. That way we can get our dependencies up to date and keep progressing with the core of Laravel.

If any JavaScript gurus out there or anyone else wants to take a stab at it, I look forward to seeing a PR or two!

**Comment by Naoray** [comment]
Guess we could use `Vue.js` for something similiar. E.g.: [Setting up ajax validation with laravel vuejs in no time](http://taha-sh.com/blog/setting-up-ajax-validation-with-laravel-vuejs-in-no-time)

**Comment by torrentalle** [comment]
Hi, 
I'm the maintainer of the project. For professional during reasons I couldn't maintain this package.....
I'm back, now I'm working on fixing some bugs and incompatibilities with recent versions.
Also I'm planning to replace jQueryValidation with [http://parsleyjs.org/](http://parsleyjs.org/) or [validate.js](https://validatejs.org/)

**Comment by austintoddj** [comment]
@torrentalle Thank you for getting back! I'll add your package back to the project as soon as you've got it sorted, really like working with it and am really grateful that you're back and it'll be maintained! Cheers! 🍻
