### ISSUE TITLE
[Suggestion] Git-flow 

### ISSUE THREAD

**Issue by reliq** [austintoddj/canvas#261]
Hi guys,

I noticed there isn't really a set principle for branching, since there's only one branch I presume. Nevertheless, I'd like to suggest [Git-flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) going forward. 

- Cheetsheet: http://danielkummer.github.io/git-flow-cheatsheet/
- Section on Atlassian's tutorials: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

What do you think?

**Comment by Naoray** [comment]
As you can see in #257 there exist one branch per feature,, but they get deleted after merging is complete.

**Comment by reliq** [comment]
@Naoray I see. It is in essence the same principle that way. However features would be prefixed with `feature/`, hotfixes with `hotfix/` and so on.

**Comment by austintoddj** [comment]
That's a fine way to go about it @reliq. I have no problem with prefixing feature branches and so on. I do clean up the branches and delete them as soon as they're merged in however just for sanity's sake.

**Comment by reliq** [comment]
Cool 👍
