### ISSUE TITLE
[Vue warn]: failed to compile template:

### ISSUE THREAD

**Issue by kylesean** [austintoddj/canvas#263]
In my local enviroment with wampserver 3.0 ,the project is normal. but when I deployed the project to the vps, I saw this being given, exactly in `http://xxxx/admin/post/1/edit`.

I am not very familiar with vue 2.0, I found some information [here](https://github.com/vuejs/vue/issues/3891), but I wonder why I am local all normal, the `edit` page on the show.

Hope you could help me,tanks a lot

**Comment by austintoddj** [comment]
@kylesean What is the error you're receiving?

**Comment by kylesean** [comment]
@austintoddj Sorry，as you can see this:
![qq 20161122220459](https://cloud.githubusercontent.com/assets/19353263/20526393/d1e32e84-b0fe-11e6-9d27-09291feea32f.jpg)

**Comment by austintoddj** [comment]
Interesting. @talvbansal Any idea on this?

**Comment by kylesean** [comment]
@austintoddj This is caused by the vue component for markdown editor

**Comment by talvbansal** [comment]
Hey guys this is really weird, Nothing has changed as far as canvas and the media manager is concerned, are you sure that all the pages resources are being downloaded?

Is there anything else you can provide us with to help diagnose the issue here?

**Comment by kylesean** [comment]
@talvbansal That's all ,so I deleted the entire project, and then re-installed, the problem is gone. I guess it should be with the cache or the integrity of the static resources.But it's so weird, it sometimes happens again.

**Comment by austintoddj** [comment]
@kylesean That is very odd to be happening. If you ever discover the source of this, please let us know on here. If this issue is resolved enough for you to continue using the application, please close the issue out. Thanks again for bringing this to our attention!
