### ISSUE TITLE
Ordering of images in media library

### ISSUE THREAD

**Issue by mhuijser** [austintoddj/canvas#265]
Hi,

I found that the ordering of the images in the Media Library is somewhat unhandy, the last uploaded image is found at the bottom of the list. Remarkable is that the date mentioned behind the uploaded file is actually a wrong one, probably that causes the faulty ordering (see attached screenshot)? The filedates on the filesystem <canvasroot>/storage/app/public/* seems just fine.

Am I missing a php module that takes care of reading the files from the filesystem correctly ? Or is it something else ? Do you guys have the same experience ?

Kind regards,

Mark

![schermafbeelding 2016-11-26 om 08 05 48](https://cloud.githubusercontent.com/assets/1103915/20638739/e9481108-b3af-11e6-842b-8f9938bc833b.png)

**Comment by austintoddj** [comment]
@talvbansal Is this something you can update from your end? 

@mhuijser Canvas uses [Media Manager](https://github.com/talvbansal/media-manager) as a media library plugin for Laravel. We'll see if we can resolve this for you as quick as possible. Thanks for bringing it to our attention!

**Comment by talvbansal** [comment]
So the ordering is based on file name, sortable lists is something I plan to look into going forward.

However good spot on the dates, i hadn't updated the filter for vue js v2 properly so it was failing and defaulting back to todays date. I've just pushed a fix up to the master branch, once I've checked a couple of other things I'll release a tag that Canvas can pull in.

**Comment by austintoddj** [comment]
Thanks for addressing this so quickly @talvbansal!
