### ISSUE TITLE
Post subtitle or excerpt

### ISSUE THREAD

**Issue by Padarom** [austintoddj/Canvas#28]
I've noticed that the subtitle of a post is not displayed in any of the templates. Was it planned to have it be displayed in the same fashion, as the tag subtitle on a tag page?

If not, would it make sense to perhaps use it as an excerpt/description to be displayed on the post overview?

**Comment by austintoddj** [comment]
Good catch @Padarom. I believe the reason I left it out was purely a design choice, just didn't have a place to put it. But it might make sense to display the subtitle on the front-end post index page underneath the title of each blog post. Or it could exist on the individual post page itself. Thoughts?

**Comment by Padarom** [comment]
I was actually thinking of the first one. I was writing some posts earlier today and thought it'd be great if I could give my readers some more information about my post other than its title before they view it. 

When I'm already on the post page, I already have the text before me, so I don't think I would need another piece of information about the post on the same page.

**Comment by austintoddj** [comment]
Yup good thought. If we were to take it one step further, if there was a pleasant way to display a thumbnail of the post image on the index page, that may even be more satisfying to scroll through. Would you want to make a pr of your proposed changes?
