### ISSUE TITLE
Why use Job?

### ISSUE THREAD

**Issue by tanteng** [austintoddj/Canvas#29]
Why use Job here?
```
    public function index(Request $request)
    {
        $user = User::findOrFail(1);
        $tag = $request->get('tag');
        $data = $this->dispatch(new BlogIndexData($tag));
        $layout = $tag ? Tag::layout($tag)->first() : 'frontend.blog.index';
        return view($layout, $data)->with(compact('user'));
    }
```

**Comment by austintoddj** [comment]
Just experimenting with a few Laravel practices. There would be many ways to accomplish this besides using a job. If you have a better way that you'd like to see implemented, send me a pr.

**Comment by tanteng** [comment]
I don't think it's the best way, the queue is used for async task, not real time.

Sorry , my English is poor.

**Comment by austintoddj** [comment]
No worries @tanteng. You are correct that jobs should be reserved for asynchronous processes. I'll see what I can do to implement that in an upcoming release.
