### ISSUE TITLE
Blog configuration settings

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/Canvas#34]
Right now, the blog configuration exists only in `config/blog.php`. This works for now, at least for the initial installation of Canvas. These values should be persisted to the database however and then be able to be modified from a Blog Settings page. 

This will streamline the blog administration for people who are a little less-familiar with Laravel to update their application settings and open this project up to a larger audience.

**Comment by naneri** [comment]
Laravel https://github.com/daftspunk/laravel-config-writer can be used to rewrite

**Comment by austintoddj** [comment]
Very nice @naneri! Question: do you think it'd be best to write to a config file or store values in the database? I'm sure there's not a right/wrong way, but what's your opinion?

**Comment by naneri** [comment]
@austintoddj Hmm... a hard question, honestly I am not sure and I don't have a lot of related experience, but I think that OctoberCMS writes directly to config file. I think there might be a reason behind their choice.

**Comment by naneri** [comment]
@austintoddj by the way, need to note, that changes to config file will interfere with Git changes, in that term storing to database would be better

**Comment by RDelorier** [comment]
There are a few packages aimed at solving this, here is just one example https://packagist.org/packages/efriandika/laravel-settings

**Comment by austintoddj** [comment]
Resolved this issue with the new command `php artisan canvas:install`
