### ISSUE TITLE
Fatal Error During Creating New Post With Images

### ISSUE THREAD

**Issue by poklin** [austintoddj/Canvas#35]
Hi Guys,

I have the recent pull request and tried to create a new post.
I received below error

> FatalErrorException in ExceptionHandler.php line 259: Allowed memory size of 134217728 bytes exhausted (tried to allocate 35309376 bytes)

when I trying to insert 1 image into the post. I am using wampserver as virtual hosting and I did try to increase the ini_set('memory_limit', '512M') still receive the error.

Sorry if I am wrong somewhere else.

**Comment by erikgall** [comment]
@poklin did this happen while uploading the image or after you inserted the image and tried to view the post that the image existed in.

**Comment by poklin** [comment]
It happened when I clicked save. So It should be while update to the Database

**Comment by austintoddj** [comment]
@poklin Let me go ahead and try to replicate the issue. I'll update you when I know more.

**Comment by RDelorier** [comment]
Here is the real error
```Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet'```
the php memory is a caused while creating the exception try running this in mysql and see if it fixes the issue
```SET GLOBAL max_allowed_packet=1073741824;```

**Comment by austintoddj** [comment]
@poklin Did the solution that @RDelorier presented above work for you? If so, I'll close this issue out.

**Comment by poklin** [comment]
@austintoddj 
Ya, it is working right now. I changed the database structure text to longtext and also set the max_allowed_packet on mysql.ini
