### ISSUE TITLE
Allow image dimensions and position to be specified from the editor

### ISSUE THREAD

**Issue by connecteev** [austintoddj/canvas#472]
Thanks for cnvs.

Suggestion: It's not possible to specify the size / dimensions or position (left align, center, right align, fixed etc) of an image from the CMS. Doing it from the views defeats the purpose of having a medium-like WYSIWYG editor.

Any plans to allow cropping uploaded images and add more image layouts soon?

**Comment by austintoddj** [comment]
You're welcome! I'll give it some thought and see what I can do. 

I don't have an idea right now on how to implement that, so if you want to take a stab at it and throw up a pull request I'd be more than happy to take a look.

**Comment by connecteev** [comment]
Not sure why I'm just seeing this now, but I just wanted to put the suggestion out there, I have my hands way too full at the moment, sadly.
Btw, props on the way you're maintaining and growing this repo, it's unparalleled.

**Comment by austintoddj** [comment]
Closing this to consolidate all editor enhancements under https://github.com/austintoddj/canvas/issues/837
