### ISSUE TITLE
Add Markdown support

### ISSUE THREAD

**Issue by connecteev** [austintoddj/canvas#542]
Personally a nice-to-have for me, but would be cool.
See https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet

**Comment by connecteev** [comment]
Example of a "dead simple" markdown editor from the official vue docs itself: https://vuejs.org/v2/examples/

**Comment by xyyolab** [comment]
Agree with @connecteev 
Canvas really easy to use. Canvas with Markdown support will be even greater 😆.
