### ISSUE TITLE
php artisan canvas:install error

### ISSUE THREAD

**Issue by shinokada** [austintoddj/Canvas#55]
After running `composer create-project austintoddj/canvas canvas` I run `php artisan canvas:install`, then I get the following error.

    [Symfony\Component\Console\Exception\CommandNotFoundException]
    There are no commands defined in the "canvas" namespace.

**Comment by austintoddj** [comment]
Thanks for finding this @shinokada. The issue came up because Packagist was not pulling the latest version of the `master` branch, leaving out the actual console command. Should be fixed now with release [v2.0.2](https://github.com/austintoddj/Canvas/releases/tag/v2.0.2)
