### ISSUE TITLE
Issue with TNTSearch

### ISSUE THREAD

**Issue by poklin** [austintoddj/Canvas#57]
Hi guys, after I combine the tntsearch features, I facing below error. Izzit my problem or I miss out some set up.

PDOException in TNTSearch.php line 297: SQLSTATE[HY000]: General error: 1 no such table: info
PDO->query('SELECT * FROM info WHERE key = 'stemmer'') in TNTSearch.php line 297
Because my database does not have the info table.

I tried to search the original tntsearch github guide. Apparently there is not additional migration needed.
Any idea?

**Comment by austintoddj** [comment]
@nticaric Any idea on this?

**Comment by nticaric** [comment]
This sounds like you tried to search on an existing codebase where you don't have the index generated. What you need to do is simply run `php artisan canvas:index`

**Comment by austintoddj** [comment]
@poklin Still having any issues with this?

**Comment by fergthh** [comment]
`Info` table is created when `createIndex` method is called from [TNTSearch](https://github.com/teamtnt/tntsearch/blob/master/src/Indexer/TNTIndexer.php#L132), which uses a sqlite database.

**Comment by poklin** [comment]
Hi Guys, 

Thanks for the assist. I get it now.

**Comment by fergthh** [comment]
@poklin  Could you solve it? Perhaps to someone with the same issue may be useful this.

**Comment by poklin** [comment]
Yup, thanks to @nticaric help.
php artisan canvas:index will do the trick. Just need to wait a while for it to do the job.

**Comment by austintoddj** [comment]
@poklin Thanks for sharing your fix with everyone. I'll close this one out now.
