### ISSUE TITLE
Class 'App\Models\TNTSearch' not found

### ISSUE THREAD

**Issue by zarincheg** [austintoddj/Canvas#58]
I face to problem with the fresh installation. When I tried to create new post I got an error:
`FatalErrorException in Post.php line 171:
Class 'App\Models\TNTSearch' not found`
after I clicked the "save" button. The same error happened with tags creation. But the post/tag was created.

**Comment by nticaric** [comment]
@austintoddj I guess this one can also be closed since it's fixed in the latest version
