### ISSUE TITLE
Customizing the Quill Editor

### ISSUE THREAD

**Issue by muffaddal** [austintoddj/canvas#642]
Hi, Thanks for the awesome CMS. Is there a way we can customize the quill editor, to show more formatting options? I am trying to integrate a font size feature, that can increase or decrease the font size. Right now I only have the H2 H3 options.

**Comment by austintoddj** [comment]
I'm glad you're enjoying it! There isn't a way to customize it at the moment. The intent was to stick as closely as possible to the editor on medium.com, but if there's enough need for these options, I'd be happy to take a look at a PR or implement them in an upcoming release.

**Comment by prodigital-design** [comment]
https://froala.com/wysiwyg-editor/inline/

**Comment by austintoddj** [comment]
@prodigital-design Thanks for that link. Never came across that package, going to go ahead and see how difficult it would be to use that here.

**Comment by austintoddj** [comment]
Closing this to consolidate all editor enhancements under https://github.com/austintoddj/canvas/issues/837
