### ISSUE TITLE
Show/Hide password button

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/Canvas#65]
**BUG:** On the Profile Privacy page, the password update form can sometimes submit by clicking the `Show Content`/`Hide Content`. Only the password should become visible/invisible, the form should ONLY submit when `Save` is clicked.

The show/hide password button currently says `Show Content`/`Hide Content`.

![6c91cac6-4b29-11e6-89ea-762479abe5ea](https://cloud.githubusercontent.com/assets/8037011/17028942/d86c041a-4f2e-11e6-8aad-15cc8e6eef7f.JPG)

 
Let's update this to simply be an icon: `zmdi zmdi-eye` to show the password and `zmdi zmdi-eye-off` to hide the password. 

The color of the icon should be the primary color blue of the app.

This functionality should also exist on the Profile Privacy page, on the password update form.

**Comment by austintoddj** [comment]
@fergthh Wrote this up for you so you'd have an official issue to run your PR against.

**Comment by RDelorier** [comment]
The submit can be prevented by adding type="button" but if changing to icon guess that won't matter anymore

**Comment by fergthh** [comment]
Hi guys! Sorry for the disappearance. I'm having trouble with my computer.
This afternoon will be the PR.

**Comment by fergthh** [comment]
Fixed with #66
