### ISSUE TITLE
UC Browser compatibility

### ISSUE THREAD

**Issue by Codey-m** [austintoddj/canvas#654]
my canvas/stats page is empty (saying I haven't posted anything) but I have . I have clicked the "ready to publish" button multiple times but the "created_at" pop-up doesn't show. And What is weird for me is that the posts do show in the database.  When I manually edited the 'published_at' column in 'canvas_posts' table,  the post appeared in the view...

**Comment by austintoddj** [comment]
Are the posts in a _Draft_ mode? Meaning, are the `published_at` dates in the database sometime in the future? 

If the timing is off, make sure your `config/app.php` timezone variable is set correctly.

**Comment by Codey-m** [comment]
"published_at" column is empty in the database

**Comment by austintoddj** [comment]
If none of the posts have a `published_at` date, then nothing will be available in the Stats page. As soon as something is published, it'll show up there. 

Since autosaving is a feature of Canvas, you're able to write, edit, and modify different parts of your post, and it'll save in a Draft mode without ever touching the "Ready to Publish" button.

What is the behavior you're expecting to see?

**Comment by Codey-m** [comment]
I understand how the feature works but I was expecting a modal to show up when I press the "ready to publish" button . which isn't working now . and if it isn't showing it means all my posts will be saved in draft mode because the modal that isn't showing up has the "publish now" button

**Comment by austintoddj** [comment]
Are there errors in the console when you click the button?

**Comment by Codey-m** [comment]
yes...
e.querySelector is not a function

**Comment by austintoddj** [comment]
What browser are you seeing this in?

**Comment by Codey-m** [comment]
ohhh ... I just tried this on Chrome and it works perfectly.... 
I was using UC BROWSER ... does it mean Canvas supports chrome only ?

**Comment by austintoddj** [comment]
I've actually only ever tested it in the three major browsers: Chrome, Safari, and Firefox. I've got no objection in adding support for others, but don't have the time immediately available to pursue that. If you'd like to take a stab at submitting a PR for that, I'd be more than happy to take a look!

**Comment by austintoddj** [comment]
Closing this since it doesn't seem to be a widespread issue. If you feel otherwise or need further help, let me know.

**Comment by Codey-m** [comment]
Hi,

I figured that alot of people don't use UC Browser - so i figured I should
stick with what works!

Thanks
