### ISSUE TITLE
Need to disable syntax module

### ISSUE THREAD

**Issue by moyus** [austintoddj/canvas#655]
The syntax module of Quill in canvas is enabled by default, which may lead to a problem.

Code block would be stored in database as format:

```
<pre class="ql-syntax" spellcheck="false"><span class="hljs-function"><span class="hljs-keyword">function</span>...
```

In that case, at frontend, I can only use **highlight.js**, other syntax packages won't work, like **prism.js**.

FIY, the code format of Quill is `<pre>...</pre>`, which don't include sub `<code>` child and language class name, could we support it?

**Comment by austintoddj** [comment]
It looks like [this answer here](https://github.com/quilljs/quill/issues/2189#issuecomment-411692250) could provide some help if adding this to the blot itself. 

As far as building support for other syntax highlighters like Prism, I'd need to dig into it and see if there's a viable solution.

Feel free to submit a PR with any proposed changes! If not, I'll see what I can do for future releases.

**Comment by moyus** [comment]
Sounds greet, I'll look into it.

**Comment by austintoddj** [comment]
Closing this for now. If you submit a PR I'd be more than happy to take a look.
