### ISSUE TITLE
Unit Tests for Models

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#68]
PHPUnit tests should be written to cover the models of the application. 

At the most basic level, these tests should cover the relationship between the models.

Example:
A `post` can have many `tags`.
A `tag` belongs to a `post`.
A `user` can have many `posts`.

The tests can be further fleshed out to protect the application from a pretty granular level.

**Comment by erikgall** [comment]
I wrote a package that attempted to create a test case specifically for this purpose. In Rails, I would say it is a lot more common to test models, relationships, and their corresponding database table. From your description, I think it would take care if this and I wouldn't mind some feedback on it/would like to see if it's something that could be used easily by others (https://github.com/erikgall/eloquent-phpunit). I can create PR that pull's it in and uses it if you would like.

**Comment by austintoddj** [comment]
Awesome @erikgall. Let me look into it a little bit and I'll get back to you!

**Comment by austintoddj** [comment]
@erikgall Really like the package that you wrote there, it's exactly the kinda thing I was envisioning. If you wanted to create a PR that brings this into Canvas, that'd be fantastic as it'll monitor a deeper level of code that hasn't been covered yet.

**Comment by erikgall** [comment]
@austintoddj Awesome. I'll pull that in and create a PR once I'm done. Thanks for taking a look at it.
