### ISSUE TITLE
Sharing the posts feature

### ISSUE THREAD

**Issue by armancodes** [austintoddj/canvas#681]
When writing a post there can be an option (like a checkbox) that a user wants to publish their post on some external places such as:
- A tweet on Twitter with the description/summary of the post
- A post on medium copied from the main site
....

It can be a useful feature

**Comment by austintoddj** [comment]
Are you intending this feature to auto-publish to these sites whenever something is published from Canvas?

**Comment by armancodes** [comment]
Yeah, It can be optional. There should be a place that the admin stores their API's and then for publishing each post, the admin will be asked if they're interested in publishing to other sites.

**Comment by austintoddj** [comment]
I like the idea of this, but it's not something that I plan to build in the near future. Thanks for the suggestion though!
