### ISSUE TITLE
Newsletter feature

### ISSUE THREAD

**Issue by armancodes** [austintoddj/canvas#682]
I feel the need for a newsletter for Canvas. It's so much important.
For instance, there can be a weekly email containing the last week's updates/posts, etc.

**Comment by austintoddj** [comment]
Thanks for the suggestion! I'll look into some possible solutions for this.

**Comment by austintoddj** [comment]
Closing this out because I don't have any plans to make it in the near future. If you want to submit a PR that addresses this I'd be more than happy to take a look!
