### ISSUE TITLE
Add an RSS feed

### ISSUE THREAD

**Issue by armancodes** [austintoddj/canvas#686]
There can an RSS containing all posts.
(Can optimize the SEO)

**Comment by austintoddj** [comment]
I like this suggestion and already have a branch `feature/feed` build out with the necessary classes to accomplish this. There's one problem though:

Canvas doesn't "know" about how posts are routed from the frontend. The `link` value in each `<entry>` [in the feed itself](https://github.com/cnvs/canvas/blob/feature/feed/resources/views/rss/feed.blade.php#L19) needs to be an absolute path to where the post can be publicly viewed. 

So, the only viable solution I can see is passing some sort of config variable to serve as the path prefix.

That would make it so, for example:

- Jim structures his frontend routes like `www.athlead.com/posts/post-slug`
- Pam structures her frontend routes like `www.theartinstitute.com/post-slug`

However, Dwight wants his to look more personalized to himself:

- He structures his routes like `www.schrutefarms.com/dwight/post-slug`
- And his brother also blogs on his platform at `www.schrutefarms.com/mose/post-slug`

When it's a dynamic routing structure, even a config variable passed to Canvas won't do the job.

I'd really like to see this feature as a part of the package, but until I find a solution that will work for all these scenarios, and more, it's stuck where it is.

**Comment by dgillier** [comment]
Maybe of interest to you  : https://www.tastethecode.com/adding-rss-to-any-laravel-site

**Comment by channaveer** [comment]
Even I use Canvas with my Laravel Blog and I have written an whole article on it. You might find it very useful https://stackcoder.in/posts/how-to-generate-rss-feeds-in-php-larvel

**Comment by channaveer** [comment]
@austintoddj I know it might be bit over asking from you. 

Since many of them will have issues with generating RSS Feeds and Sitemap Can you please include my article links in the documentation. 

Not only mine. But any other article/packages links which can help to grow the Canvas Community. I am damm sure many of them will surely find the articles/packages very useful

**Comment by prodigital-design** [comment]
> @austintoddj Я знаю, что это может быть немного больше, чем просить от вас.
> 
> Поскольку многие из них будут иметь проблемы с созданием RSS-каналов и карты сайта, пожалуйста, включите ссылки на мою статью в документацию.
> 
> И не только моя. Но любые другие статьи/пакеты ссылок, которые могут помочь расширить сообщество Canvas. Я чертовски уверен, что многие из них наверняка найдут статьи / пакеты очень полезными

This works with the link view domain.com/username/feed ?

**Comment by channaveer** [comment]
@prodigital-design yea it does

**Comment by austintoddj** [comment]
Closing in lieu of #923.
