### ISSUE TITLE
Application Controller tests

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#69]
PHPUnit tests should be written to cover the controllers of the application. 

At the most basic level, these tests should cover the controller responses and data passed back and forth between the controller methods and views.

Example:
The `index()` method in the **PostController** should return a view, with `$data` passed to the view.

These tests can be further fleshed out to protect the application from a pretty granular level.

**Comment by foxted** [comment]
How do you want to proceed on this one? 

We could update the existing tests to include an assertion on the view data like so: 

```php
    /**
     * Test the response code for the Blog page.
     *
     * @return void
     */
    public function testBlogPageResponseCode()
    {
        $response = $this->call('GET', '/');
        $this->assertEquals(200, $response->status());
        $this->assertViewHasAll(['posts', 'tag']);
    }
```

**Comment by austintoddj** [comment]
Yes I like what you've got there. Let's use that.
