### ISSUE TITLE
Migrating from Wink to Canvas

### ISSUE THREAD

**Issue by CraftLogan** [austintoddj/canvas#693]
Hello, I am wondering if there is a guide to convert a wink blog to canvas? I currently have a wink blog up and going how much working am I looking at to convert it all over to canvas? Is there some command already built that could convert the wink database to the canvas one? Thanks, Logan

**Comment by austintoddj** [comment]
There isn't a guide written, no. The amount of work would be pretty minimal, and I'd be more than happy to walk through it with you. Shoot me an email at austin.todd.j@gmail.com and we can get it taken care of.

**Comment by CraftLogan** [comment]
Thank you @austintoddj I appreciate your response. I will get in touch with you sometime just been covered up lately. Thanks Logan

**Comment by austintoddj** [comment]
Closing this unless more help is needed.
