### ISSUE TITLE
Consider removing mcrypt

### ISSUE THREAD

**Issue by Swader** [austintoddj/Canvas#7]
[More info here](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong), basically, stay away from mcrypt, there's a bunch of better alternatives.

**Comment by austintoddj** [comment]
Where are you seeing any usages of mcrypt? Just want to make sure we're looking at the same thing.

Thanks for the help!

**Comment by Swader** [comment]
I merely noticed it in the system requirements, have not had the chance to use it yet. Why is it required?

**Comment by austintoddj** [comment]
That was actually left over from older [Laravel 5.0 documentation](https://laravel.com/docs/5.0#server-requirements). Thanks for catching that!

Fixed with commit : [f6a59a8cf35ec44f9f6021ad6a69e524a6861101](https://github.com/austintoddj/Canvas/commit/f6a59a8cf35ec44f9f6021ad6a69e524a6861101)
