### ISSUE TITLE
Create Link To Sections Of Same Page

### ISSUE THREAD

**Issue by channaveer** [austintoddj/canvas#740]
Hi I was wondering if we can do the internal section links

Eg:

Contents

1. Something (When I click on this it must take me to the 1. Something down)
2. Nothing

/** Other content **/ 

1. Something

Kindly let me know how to achieve it. 

I am using canvas 5.3 version.

**Comment by austintoddj** [comment]
Are you talking about in the editor itself, similar to linking markdown anchors?

**Comment by channaveer** [comment]
Yes. Kind of that way.

Even if we can do via anchor with **id** then that's also fine.

**Comment by austintoddj** [comment]
Closing this to consolidate all editor enhancements under https://github.com/austintoddj/canvas/issues/837
