### ISSUE TITLE
Globally accessible stats/taxonomy

### ISSUE THREAD

**Issue by canatufkansu** [austintoddj/canvas#750]
I opened a blog using the Canvas, now multiple users are posting their article into the system. But when I try to display statistics I only see mine stats and I cannot manage topics or tags as an administrator.

Is there a quick way to manage system wide settings and stats ?

Thank you,

**Comment by austintoddj** [comment]
At this time, no there aren't any roles/permissions implemented. This could definitely be a good feature, but I just haven't had the time to work on it yet.

**Comment by austintoddj** [comment]
After thinking about this for just a minute, I wonder what your thoughts are on this?

Instead of having roles/permissions, what if on the Stats page, you could toggle between global stats, and only yours? This doesn't change the fact that settings, tags, and topics are still user-specific, but at least you could review stats on the entire blog if you cared to.

**Comment by canatufkansu** [comment]
That would be nice actually ! At least everyone could review global stats. Which is totally fine for most of the use cases.

About the tags and topics, I couldn't get the idea why everyone have their own tags and topics. At least Topics should be managed. Usually a blog has one owner/company/organization and needs to be moderated, without moderation of these things there is no way I can manage the blog site.

For example, I installed Canvas for my product web site and I created 3 main topics which are News, Technology and New Features. On the mydomain.com/blog I created links for these topics, so all posts that are written by all authors will be summarized under these 3 topics.

But now when I say to an author to put his/her post under Technology, they need to create a new Topic which is not the one I created. So I have to go to DB and change the foreign keys of their post topics.

At least when an Author adds new Topic system can check the name and suggest the one that exists already. How about that ? It is relatively easy to implement as a feature and doesn't need any administration.

**Comment by austintoddj** [comment]
Ok, I think this could work. 2 actionable steps to make this complete:

- Globally accessible stats
- Globally accessible taxonomy (still can only be edited/removed by the owner, but can be utilized by anyone)

**Comment by dgillier** [comment]
Thanks @austintoddj  , Globally accessible stats will be great, globally accessible taxonomy is a great step too...

But personnaly like @canatufkansu, I still think Topics should be set by admin only...

**Comment by christopherokonkwo** [comment]
Has this feature been implemented yet?

**Comment by austintoddj** [comment]
@christopherokonkwo Not yet. v6 is deep in development and includes a basic roles feature. With it, only Admin users will have the ability to access the /tags /topics pages. Global statistics is absolutely possible, but hasn't been implemented yet.

**Comment by austintoddj** [comment]
Added in [v6.0.0](https://github.com/austintoddj/canvas/releases/tag/v6.0.0)
