### ISSUE TITLE
Whether or not to set up StyleCI

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/Canvas#76]
Want your feedback here.  I was looking into setting up [StyleCI](https://styleci.io) to maintain a consistent code style throughout the app. In your opinion, would this make it more difficult for you guys creating pull requests, or would this be a good thing to make sure it's got the same format every time you touch it? Not a wrong answer here, just want to get some feedback before implementing something that would essentially set the standard for commits/merges.

**Comment by RDelorier** [comment]
Seems like a good idea. They even have a [Laravel preset](https://styleci.readme.io/docs/presets#laravel) ready to go 🎉

**Comment by fergthh** [comment]
:+1:  It sounds like a very good idea! I think that when a project begins to grow fast, it's time to keep a certain order and clear rules order to ensure a good future.

**Comment by austintoddj** [comment]
Thanks for the insight guys! Either of you have experience in setting it up at all? @RDelorier @fergthh

**Comment by austintoddj** [comment]
Got it set. Thanks again guys for the input, here's to clean coding!
