### ISSUE TITLE
The Mix manifest does not exist.

### ISSUE THREAD

**Issue by SwapnilAkolkar** [austintoddj/canvas#760]
Facade\Ignition\Exceptions\ViewException
The Mix manifest does not exist. (View: C:\xampp\htdocs\blog\vendor\cnvs\canvas\resources\views\layout.blade.php)

**Comment by SwapnilAkolkar** [comment]
while executing the url 
http://localhost/blog/public/canvas

**Comment by austintoddj** [comment]
Could you try publishing the assets again and let me know what you see?

```
php artisan canvas:publish
php artisan view:clear
```

**Comment by itsmysterybox** [comment]
@SwapnilAkolkar Have you installed npm dependencies?
