### ISSUE TITLE
TestItCreatesPost Failing Intermittently

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/Canvas#78]
On the `PostTest.php` method `testItCreatesPost`, PHPUnit will intermittently fail with this error:

<img width="969" alt="screen shot 2016-07-25 at 8 36 52 pm" src="https://cloud.githubusercontent.com/assets/8037011/17123272/ff4704aa-52a7-11e6-90e2-ca493e22f73a.png">

This has happened on multiple occasions and breaks the TravisCI build, but can be fixed with pushing another bogus commit, basically making the build restart. So running PHPUnit two times will produce different results, occasionally causing the bug.

@RDelorier Maybe you know what could fix this?

**Comment by RDelorier** [comment]
Most likely the Carbon::now() being called twice, if you store it in a var (or just leave out the created_at field) it should fix it.

**Comment by austintoddj** [comment]
Thanks @RDelorier! Gonna try that right now.

**Comment by austintoddj** [comment]
Worked like a charm @RDelorier. Storing the carbon instance in the variable was the key.

**Comment by RDelorier** [comment]
Glad that fixed it, inconsistent test results are a pain :/
