### ISSUE TITLE
Show/Hide password icons interrupt input navigation

### ISSUE THREAD

**Issue by RDelorier** [austintoddj/Canvas#80]
Just finished setting up a site and noticed that tabbing through the password fields will stop on the show/hide icons. Should those links have tabindex -1 or is that intended?

**Comment by austintoddj** [comment]
Not intended. Just checked it in Safari and Chrome, and it appears to only affect Chrome. If you want to make a PR for it and Chrome/Firefox/Safari all work as expected, I'll merge it in right away. Good catch @RDelorier!

**Comment by RDelorier** [comment]
Whew what a day, I'll get a PR open in just a few!
