### ISSUE TITLE
Add styles for right to left languages

### ISSUE THREAD

**Issue by hasanparasteh** [austintoddj/canvas#806]
Hey I was using your packages which was great and I find out when I change locale to `fa` the dashboard theme and text won't change to RTL! so it came to my mind to add somehow this feature to your GitHub repository..
Is this feature is under construction or can I made that one for you?

**Comment by austintoddj** [comment]
It's not in progress at this time, so if you want to submit a PR I'd be more than happy to take a look!

**Comment by hasanparasteh** [comment]
OK, I'm on it

**Comment by austintoddj** [comment]
Added in [v6.0.0](https://github.com/austintoddj/canvas/releases/tag/v6.0.0)
