### ISSUE TITLE
[Suggestion] Integrate better mardown editor

### ISSUE THREAD

**Issue by karlmonson** [austintoddj/canvas#81]
I would love to see a better markdown editor integrated into this platform. Right now it's painfully difficult to write in markdown with the current text editor. Perhaps something like http://ghosditor.herokuapp.com/.

**Comment by austintoddj** [comment]
Good suggestion @karlmonson. Having a dual-pane editor and preview mode would sure be an enhancement. Currently yes, you can either paste your markdown into the `</>` code view in the WYSIWYG or you can just write it verbatim.

**Comment by fergthh** [comment]
:+1 to enhancement editor. But the *ghosditor project* is inactive since a year. I would suggest perhaps see a more active project such as [Showdownjs](https://github.com/showdownjs/showdown).

**Comment by Swader** [comment]
Showdown is really good and easy to extend, we use it internally at SitePoint. It also plays well with PHP's commonmark if needed.

**Comment by foxted** [comment]
I just installed Canvas to use for my personal website, trying to write my first post, I noticed the editor feels really bloated.

I would suggest an editor in a Medium fashion, to be able to focus on writing. No need for font customization, alignment, etc... Just simple editor.

I will try to search see if I can find a decent Medium-like editor.

**Comment by austintoddj** [comment]
Great thoughts guys. Looking forward to seeing what we can do to improve the project as a whole. I agree, a minimal, strictly markdown editor would be far more appropriate for Canvas.

**Comment by foxted** [comment]
@austintoddj Are you open to pull-request on this? Seems like this library might be good for the job https://simplemde.com/.

**Comment by austintoddj** [comment]
@foxted Yes, that looks like an excellent solution. If you wanted to make a PR that replaced Summernote with SimpleMDE, I'd certainly pull it in.

**Comment by austintoddj** [comment]
UPDATE: Just created a `develop` branch in which I replaced Summernote with SimpleMDE. Looks nice so far, just a few more tweaks from here before we can merge. If any of you JavaScript ninjas want to take a stab at it, please feel free.

**Outstanding issues:** 

* The `Full Screen` feature works, but it sits right behind the navbar on top, causing some text to be hidden.
* The `Split Pane` editor is doing the same thing, sitting behind the navbar. 
*  The `?` help button brings us to a new page with help topics. Can we just make the help topics pop up in a modal like the Summernote editor had?

Any help is greatly appreciated!

@foxted @karlmonson @fergthh @talv86 @RDelorier @tirjok

**Comment by austintoddj** [comment]
@karlmonson @Swader Hope you guys like the new Markdown editor, should be much more pleasant now writing with Canvas! :)

**Comment by karlmonson** [comment]
@austintoddj Thank you! Giving it a try now.
