### ISSUE TITLE
Unsplash image not populated in custom frontend ( i.e. "featured_image" element is Null even though image saved on backend)

### ISSUE THREAD

**Issue by phrane** [austintoddj/canvas#813]
Steps:
1. setup Unsplash integration via adding API key in canvas.php ( mine steps as follows:
 'unsplash' => [
        'access_key' => env('CANVAS_UNSPLASH_ACCESS_KEY', 'xxxxxxxxxxxxxxx_my_access_key_xxxxxxxxxxxxxxxxxxxxxxxxxxc'), ],  )

2. Create a blog on backend and add an image using the unsplash integration - i.e. select an image.

3. Image is shown on backend. Complete and save the blog.
4. View image on frontend.

Expected:
Image saved from backend should be displayed on frontend. Hence, checking the "featured_image" element should show reference to the image.
Actual: 
When calling the "featured_image" element on frontend view, it is "Null", and no image is displayed on frontend even though image is present on saved backedend form. 

Addtional: 
When selecting an image from local hdd to save on blog (in backend), this IS viewable on the frontend, and the "featured_image" element is populated as expecteded.

**Comment by austintoddj** [comment]
So, the `featured_image` field has a value in the database, but it's not showing up when you try to render it in your custom frontend?

**Comment by phrane** [comment]
Not quite. The "featured_image" field has a Null value in the database and was not rendering in the front end. Note, I was expecting the featured_image to appear in the body section of the post, and raised this issue because no images were rendering in the front end.

However, this morning following a reboot, unsplash images are rendering on the frontend body AND I have realised that the featured_image pertains to top image on the post, and this is also rendering on the front end.
A brief check on the database also shows the feature_image field populated as expected.
![backend](https://user-images.githubusercontent.com/34143543/92235991-83b9d100-eeac-11ea-8c77-e8184d3743db.png)
![frontend](https://user-images.githubusercontent.com/34143543/92236004-887e8500-eeac-11ea-8875-fe1a31efbd11.png)
![array_dump](https://user-images.githubusercontent.com/34143543/92236016-8caaa280-eeac-11ea-8898-2629c436d57d.png)
