### ISSUE TITLE
[Suggestion] Preview mode

### ISSUE THREAD

**Issue by Swader** [austintoddj/Canvas#82]
Any way to preview posts before publishing them? If not, maybe add it? Really important, especially when people have RSS feeds.

**Comment by austintoddj** [comment]
Thanks for asking @Swader! There is currently a way to preview. If you create a post, save it as a draft, and look at the main posts index page, the `Actions` column will have a magnifying glass icon.
Example:
<img width="150" alt="screen shot 2016-08-01 at 5 49 24 pm" src="https://cloud.githubusercontent.com/assets/8037011/17311376/937f95f2-5810-11e6-8786-f1b3313e1c88.png">

That will allow you to see what it looks like. But you're right, and I think I'll throw a preview button on the `edit` page itself to make it even more user friendly.

**Comment by Swader** [comment]
Ahh, found it, thanks!
