### ISSUE TITLE
Activating Markdown Mode

### ISSUE THREAD

**Issue by Swader** [austintoddj/Canvas#83]
I have pasted some MD into the editor, but the post renders in plaintext, it doesn't convert the MD into HTML. Is there something extra I need to do to make sure this works?

**Comment by austintoddj** [comment]
You pasted the markdown in the editor, saved it and then previewed the page?

**Comment by Swader** [comment]
Yes

**Comment by Swader** [comment]
The current editors is somewhat useless for writing, so I write in something else (Classeur, or MacDown) and paste it in.

**Comment by Swader** [comment]
Got it, thanks. Definitely needs a better editor, though :/
