### ISSUE TITLE
Image enhancements in the editor

### ISSUE THREAD

**Issue by mm11jb** [austintoddj/canvas#832]
The images added can be huge and always aligned center.

Could you add backend fields to set the image height, width and alignment?

**Comment by austintoddj** [comment]
Would love to have that type of functionality built into it. With the v6 release coming up, I can't dedicate time to it right now, but I'm open to looking into this in the future. There are other editors out there that I'd consider building into Canvas, such as:

- [Dante](https://michelson.github.io/dante2/)
- [TipTap](https://tiptap.dev/)

**Comment by mm11jb** [comment]
Dante appears to be more feature rich but TipTap is Vue based. Hard call, but I don't think Canvas needs too many more features in the editor. Just some basic improvements such as this.

**Comment by austintoddj** [comment]
I agree. Once v6 is out, I can start looking into enhancing the editor. 

Closing this out to keep everything "editor-related" in one spot here: https://github.com/austintoddj/canvas/issues/837
