### ISSUE TITLE
Editor enhancements

### ISSUE THREAD

**Issue by austintoddj** [austintoddj/canvas#837]
While [Quill.js](https://quilljs.com/) is a powerful tool with great editing capabilities, it'd be helpful to have other options when it comes to an editor. Some of the viable packages we could include here are:

- [TipTap](https://tiptap.dev)
- [Dante](https://michelson.github.io/dante2)

I'm sure there are more. This at least gets us started on ways to improve the editing experience with Canvas. 

## Feature requests
- Specify the size/dimensions or position (left align, center, right align, fixed etc) of an image
- [Liquid tags](https://github.com/austintoddj/canvas/issues/541)
- Markdown support
- "Link-to" sections within a post
- Scientific notation support
- HTML5 video support
- Link customization (follow, nofollow, specify targets)

**Comment by thenexxuz** [comment]
For the link customization, can the target also be specified please.

**Comment by secrethash** [comment]
Dante looks great. Better than Quill.js

**Comment by mrcrandell** [comment]
For enhancements to the editor, I'd like to see a "clear formatting" button. This would be especially useful when toggling the "code block" button as some words/characters keep special formatting.

**Comment by sahil1572** [comment]
Thumb generation option must be there for featured images , with 10 post each 3 MB its taking 30 MB to load in canvas-UI

**Comment by austintoddj** [comment]
@sahil1572 Could you expand on that a bit more? Just want to make sure I know what you're getting at.

**Comment by sahil1572** [comment]
![image](https://user-images.githubusercontent.com/5916432/95330629-6ff7f500-08c6-11eb-91da-241b25dfb67d.png)
these images on home page category and tag listing pages  need to be cropped as they are being served in full size .

**Comment by JeremyChb** [comment]
In addition to scientific syntax, it must me awesome to allow the integration of nice tables and charts (chart.js could be awesome for that : https://github.com/chartjs/Chart.js)

**Comment by austintoddj** [comment]
Closing this in favor of opening a [discussion here](https://github.com/austintoddj/canvas/discussions/919).

**Comment by Shepherd345** [comment]
Laraberg editor will solve the editing experience. Because, the editing experience with canvas is very poor at the moment. Is there a way to change the editor at our end?
