### ISSUE TITLE
HTML5 video support

### ISSUE THREAD

**Issue by thenexxuz** [austintoddj/canvas#840]
Have the ability to upload various types of videos (mp4, webm, ogv, etc) or provide a URL to a video but also allow live streaming URLs like HLS or RTMP. Having just a simple `<video>` tag with the `<source>` tag would be all that is needed and could be styled easily on the UI side.

**Comment by austintoddj** [comment]
Added this to the list of feature requests, closing this to keep editor enhancements consolidated here: https://github.com/austintoddj/canvas/issues/837
