### ISSUE TITLE
How to add rules to individually define image size for featured image?

### ISSUE THREAD

**Issue by hexpit** [austintoddj/canvas#842]
I dont understand vue. I want to define rule for image size only in featured image upload option. How to achieve this?

**Comment by austintoddj** [comment]
Are you just trying to size it differently on the frontend? From the editor itself, the featured image is nothing more than a path to the image. You can define the size however you'd like on the public-facing side.

**Comment by hexpit** [comment]
Every user is free to upload featured image with his own choice and it will create an impact on frontend presentation. I want it to be done by validation rules without touching the package itself. Please help me out.

**Comment by austintoddj** [comment]
There's really no need for validation rules, since the presentation of the post and its featured image are handled outside of this package. If you're referring to images _within_ the editor, then yes, this package handles them.
