### ISSUE TITLE
uploaded images are not displaying on canvas studio frontend (on my hostgator site)

### ISSUE THREAD

**Issue by phrane** [austintoddj/canvas#843]
Description:
On local ubuntu dev machine: After installing canvas and canvas studio in my application, and creating a blog post with featured image uploaded and everything is fine, images are displayed on frontend.

Hostgator webhost: After git cloning my site across to hostgator, my blog entry no longer displays uploaded images. No alteration to the canvas.php is made from default settings. 
Note, I had to move all contents from the laravel "public" folder into the root (www) for hostgator to serve the site. Hence public/ was empty, but I ran "storage:link" to create the symbolic link in there from public to storage/ .
One further point to add is that the image files are being saved on the host local storage location as expected (and i can view from within host c-panel), but navigating via web browser does shows 404|not found error.

Thanks

**Comment by austintoddj** [comment]
So the images stored in `public/storage` are going to ignored when performing a git clone. I'm assuming this is the issue, just from not seeing the entire setup myself.

A quick fix would be to get the `public/storage/canvas/` directory over to your hosted app, and then all the paths should be linked up since you already ran the `storage:link` command.

**Comment by austintoddj** [comment]
Let me know if you have any further questions on it. 

If you do run into more issues, go ahead and file any relevant bugs [here](https://github.com/austintoddj/studio/issues).

**Comment by phrane** [comment]
Hey Todd, thanks for getting back.
Still doing some further investigations on my setup/config which is likely the issue. Will loop back if i have further problems.

Note, If i manually create and save files to ~/www/storage/canvas/images then images and avatar display, but files are  saved here: ~/www/storage/app/public/canvas/images/ which is not being picked up. 

Hostgator dictates that root laravel app folder is outside of www, with only public/ contents copied across to www/

Thanks for now,
P

**Comment by austintoddj** [comment]
I'll help out however I can, let me know what you find.
