### ISSUE TITLE
Image Uploads Fail on when domain/subdomain is set

### ISSUE THREAD

**Issue by daltonsutton** [austintoddj/canvas#855]
I've noticed that when I set the domain in the canvas.php config file, image uploads don't seem to work for me. I've tried both local and S3. However, when I set that back to null and use the path instead, image uploads work.

**Comment by austintoddj** [comment]
Is this happening when you change both the domain and subdomain, or just one without the other?

**Comment by daltonsutton** [comment]
It happens when I set the domain to "admin.canvas.test" and set the path to just simply, "" - an empty string.

**Comment by austintoddj** [comment]
I'll see if I can get this fixed by tonight or tomorrow @daltonsutton.

**Comment by daltonsutton** [comment]
Thanks @austintoddj, mostly just wanted to report it, I'm not in any rush. Great work with Canvas!

**Comment by austintoddj** [comment]
Fixed in https://github.com/austintoddj/canvas/releases/tag/v6.0.5
