### ISSUE TITLE
session conflict with Laravel jetstream insalled on Laravel 8 

### ISSUE THREAD

**Issue by sahil1572** [austintoddj/canvas#859]
i have installed **_Laravel /jetstream_** with 
php artisan **jetstream:install livewire** --teams  , 
Now my canvas has stopped working , i think session are conflicting in same way in both of them 

this is the error i'm getting now why submit login form on canvas 
`SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'f1f2ef68-b808-4902-ad34-db7653ea34d8' for column `mydb`.`sessions`.`user_id` at row 1 (SQL: update `sessions` set `payload` = YTo1OntzOjY6Il90b2tlbiI7czo0MDoiVGJwTG51ZHptR1FUUXZqb2V1VENVRjZsZ3Uwa3VnSW9l
d0xDTkp6ZSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6
e319czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MjU6Imh0dHBzOi8vbG9jYWwudGVz
dC9jYW52YXMiO31zOjM6InVybCI7YToxOntzOjg6ImludGVuZGVkIjtzOjI1OiJodHRwczovL2xv
Y2FsLnRlc3QvY2FudmFzIjt9czo1MzoibG9naW5fY2FudmFzXzU5YmEzNmFkZGMyYjJmOTQwMTU4
MGYwMTRjN2Y1OGVhNGUzMDk4OWQiO3M6MzY6ImYxZjJlZjY4LWI4MDgtNDkwMi1hZDM0LWRiNzY1
M2VhMzRkOCI7fQ==, `last_activity` = 1602076576, `user_id` = f1f2ef68-b808-4902-ad34-db7653ea34d8, `ip_address` = 104.93.174.162, `user_agent` = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 where `id` = 9vpcAQVca2CDx7YD7V0386TUVAJUJxZIXFZc3R7q)
`
 session table 
![image](https://user-images.githubusercontent.com/5916432/95336713-99b51a00-08ce-11eb-83b1-00b6d9065aea.png)

![image](https://user-images.githubusercontent.com/5916432/95336751-a33e8200-08ce-11eb-925a-2ca0ff4e8d37.png)

**Comment by austintoddj** [comment]
You can find some clarification and workarounds in this issue: https://github.com/austintoddj/canvas/issues/851
