### ISSUE TITLE
UUID not compatible with users table

### ISSUE THREAD

**Issue by JeremyChb** [austintoddj/canvas#862]
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'user_id' at row 1 (SQL: update `sessions` set `payload` = [...], `last_activity` = 1602582982, **`user_id` = 31a80d8f-086c-4289-b6ed-e467cf041c9d**, `ip_address` = ::1, `user_agent` = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 where `id` = fS7SZ2ZbvoTXqtQuiHb3HtikPguzXlecsz9D1iy9)

But the users table used in core laravel uses a bigint for user_id

**Comment by austintoddj** [comment]
This is a conflict because of integrating Jetstream. You'll be able to find some clarification and workarounds in this issue: https://github.com/austintoddj/canvas/issues/851

**Comment by JeremyChb** [comment]
An other solution would be to use https://github.com/goldspecdigital/laravel-eloquent-uuid to override User model and the migrations user & session tables to use UUID in the core laravel project.
Just tested and works great

**Comment by austintoddj** [comment]
Awesome, thanks @JeremyChb. I'll update the workaround in #851 so this is another option for people.

**Comment by JeremyChb** [comment]
I still have a problem but can't find if it's linked to that or not.
In the setup part I'm not able to change de locale or the light/dark theme, the route called doesn't contain /canvas :
![image](https://user-images.githubusercontent.com/13405982/95863078-0b281900-0d64-11eb-926c-66348534a870.png)

**Comment by JeremyChb** [comment]
The link called looks like http://domain/api/users/4252d1c2-eb38-4da5-bf9e-826cfe5c6207

**Comment by austintoddj** [comment]
Actually came across that bug myself this morning. Pushing a fix in just a bit here.

**Comment by JeremyChb** [comment]
Oh nice ! Thank you ! So if it's not linked, the workaround with the package I mentioned above is definetly a good solution

**Comment by austintoddj** [comment]
I added a little snipped in the comment on the issue and dropped your fix in there. Hope it helps some others get past the issue!

**Comment by JeremyChb** [comment]
Maybe it's something you can put directly in the readme, as it seems to be a problem for many people

**Comment by JeremyChb** [comment]
I'll later, have to go. But I'll let you know for sure !
Also, do you want me to provide good translations for french ? They are not correct currently.

**Comment by austintoddj** [comment]
That would be fantastic! Since I have to rely on Google Translate for getting these in the app, I'll absolutely defer to someone who actually knows the language more.

**Comment by JeremyChb** [comment]
OK I'll do it.

Regarding the previous bug, it's not fixed on my side. Not fully at least. It's OK for the first http calls (posts to users on my scrrenshot) but not for the last red line (happens when I want to change a parameter in the setup page)

**Comment by austintoddj** [comment]
There is an active bug out there right now, dealing with saving posts. #863 details the problems, and I'll try and get them patched tonight.

**Comment by JeremyChb** [comment]
Ok ! Will let you know for the translations when it's done

**Comment by JeremyChb** [comment]
Pull request is alive !

**Comment by austintoddj** [comment]
Fantastic, thanks!

**Comment by JeremyChb** [comment]
Any news about the routes bug we talked above ?

**Comment by austintoddj** [comment]
@JeremyChb After updated by and publishing the assets, it still persists?

**Comment by austintoddj** [comment]
Are you defining paths in your `.env` file for Canvas?

**Comment by Braunson** [comment]
Seems this is still a bug (fresh install today).

**Comment by Braunson** [comment]
@austintoddj Yes I was using the database, saw the mentioned thread solution above and tried `file` driver, same issue occurred.

**Comment by Braunson** [comment]
@austintoddj I did not clear cache, will give it ago when I reinstall canvas, I ended up using Wink instead that day.
