### ISSUE TITLE
Sign out.

### ISSUE THREAD

**Issue by SystemAdm** [austintoddj/canvas#867]
I can't sign out properly in Laravel 8.1
The page is reloading when I click the link, but I'm still logged in.
![canvas](https://user-images.githubusercontent.com/5839296/96363377-3def5a00-1134-11eb-9acb-03beda1159c2.png)

**Comment by austintoddj** [comment]
What does the network tab look like if you have that open when you try and logout?

And do you have any paths defined for Canvas in your `.env` file?

**Comment by austintoddj** [comment]
Thanks for bringing this up @SystemAdm. Let me know if you have any more issues.
