### ISSUE TITLE
Command "canvas:ui" is not not defined

### ISSUE THREAD

**Issue by junoir** [austintoddj/canvas#869]
![php artisan canvas ui](https://user-images.githubusercontent.com/4056213/96563539-57261100-12c2-11eb-9944-8093cf509c90.png)
I got this error after I did a fresh install of laravel and canvas. after i linked storage and run command php artisan canvas:ui i get error  canvas:ui is not defined

**Comment by austintoddj** [comment]
@junoir Can you verify what version of Canvas/Laravel you're using?

**Comment by junoir** [comment]
im using "austintoddj/canvas": "^5.4", and 
laravel "laravel/framework": "^7.24",

**Comment by austintoddj** [comment]
Thanks for that info. 

So the `canvas:ui` command was re-introduced into the project in [v6.0.2](https://github.com/austintoddj/canvas/releases/tag/v6.0.2). If you go ahead and follow [this upgrade path](https://github.com/austintoddj/canvas/blob/master/.github/UPGRADE.md#upgrading-to-600-from-54), you'll have access to the command. 

If you have any questions while going about it, feel free to reach out.
