### ISSUE TITLE
Is it possible to publish the backend admin code?

### ISSUE THREAD

**Issue by tosettil-polimi** [austintoddj/canvas#872]

**Comment by austintoddj** [comment]
Unfortunately, no. If there's something you'd like to see added feel free to [add a feature request](https://github.com/austintoddj/canvas/issues).

Or, check out the [contribution guide](https://github.com/austintoddj/canvas/blob/master/.github/CONTRIBUTING.md#setup) to add anything you like. Then, submit a PR and I'll gladly review it!
