### ISSUE TITLE
Canvas keeps redirecting when canvas domain is set

### ISSUE THREAD

**Issue by christopherokonkwo** [austintoddj/canvas#878]
When I set subdomain in canvas config, the canvas-ui works fine but the /canvas keeps redirecting to /subdomain/stats instead of  /stats. 
Example if subdomain is` blog.example.test` then it keeps redirecting to `https://blog.example.test/blog.example.test/stats`

**Comment by austintoddj** [comment]
First, you should add the `CANVAS_DOMAIN` variable to your `.env` file.

Second, is your subdomain defined as a fully qualified URL? (ie. http:// or https://)

**Comment by christopherokonkwo** [comment]
My subdomain is not fully qualified URL.

**Comment by austintoddj** [comment]
If you use a fully qualified URL in the `CANVAS_DOMAIN` variable, does the issue resolve?

**Comment by christopherokonkwo** [comment]
```
The bug is from this line of code.
    /**
     * Return the configured public path url, prioritizing a subdomain.
     *
     * @return string
     */
    public static function basePath(): string
    {
        return config('canvas.domain') ?? '/'.config('canvas.path');
    }

I fixed it by changing tweaking it a bit.

    /**
     * Return the configured public path url, prioritizing a subdomain.
     *
     * @return string
     */
    public static function basePath(): string
    {
        return config('canvas.domain') ? '/' : '/'.config('canvas.path');
    }`

**Comment by christopherokonkwo** [comment]
Now above fix works with the assumption that on sub domain theirs no need for `config('canvas.path')` and hence set to null.
But after further testing, I found out that `config('canvas.domain')` is not necessary in this function
```
    /**
     * Return the configured public path url, prioritizing a subdomain.
     *
     * @return string
     */
    public static function basePath(): string
    {
        return config('canvas.domain') ?? '/'.config('canvas.path');
    }

Therefore having this will work absolutely fine.

 public static function basePath(): string
    {
        return '/'.config('canvas.path');
    }

**Comment by christopherokonkwo** [comment]
Also I think that the docs should reflect that `config('canvas.path')` can be set to null if you don't want a prefix to your canvas route.

**Comment by austintoddj** [comment]
Thanks for providing that. I'd be more than happy to review a PR if you'd like to submit one, I think it'd be a helpful change.

**Comment by christopherokonkwo** [comment]
Alright then. I'll do that.
