### ISSUE TITLE
Change of user when admin publishes the post

### ISSUE THREAD

**Issue by blankRSD** [austintoddj/canvas#879]
### Basic Info
- Laravel v8
- Canvas v6
---
### Description
A contributor writes a post and saves it as a draft. Once the admin reviews the post and publishes it, the user for the post changes from the contributor to the admin. The contributor then no longer can see the post in his posts section.

I believe this error is due to the following line in `src/Http/Controllers/PostController.php` line number 102

```php
$post->user_id = $request->user('canvas')->id;
```
The user('canvas') return the currently signed in user which is the admin. Hence the user changes from the contributer to the admin.

**Comment by austintoddj** [comment]
Yep, you're right. I'll get a fix out for this shortly.
