### ISSUE TITLE
Editor is unable to publish the post

### ISSUE THREAD

**Issue by blankRSD** [austintoddj/canvas#880]
### Basic Info
- Laravel v8
- Canvas v6
---
### Description
An editor is unable to publish the post written by the contributor. The error can be seen in the console as follows:
![image](https://user-images.githubusercontent.com/24247542/97797827-38bb0080-1c46-11eb-8d1d-53e2dbb6ac05.png)

I believe the error is due to the following condition in the `store` method in `src/Http/Controller/PostController.php`
```php
if ($request->user('canvas')->isAdmin) {
    $post = Post::with('tags', 'topic')->find($id);
} else {
     $post = Post::with('tags', 'topic')->where('user_id', $request->user('canvas')->id)->find($id);
}

if (! $post) {
    $post = new Post(['id' => $id]);
}
```

Here since the signed-in user is an editor and `user('canvas')->id` returns the id of the editor, thus the post is not being found. Hence a new post is created which results in Duplicate Entry error.

**Comment by austintoddj** [comment]
I'll get this fixed shortly.
