### ISSUE TITLE
Upload image from the editor

### ISSUE THREAD

**Issue by orenguyster** [austintoddj/canvas#89]
Hi
When i trying to upload an image from the post editor it shown me an error : Allowed memory size of 536870912 bytes exhausted (tried to allocate 213829600 bytes)

At the beginning i thought it's php.ini issue but after I doubled (more than once) the max  size upload the the post size it's doesn't look like it's fixing it.
Thanks

**Comment by RDelorier** [comment]
Maybe it's the MySQL limit, see #35

**Comment by austintoddj** [comment]
You're right @RDelorier, sounds like this is a duplicate issue. @orenguyster can you try and implement the solution detailed [here](https://github.com/austintoddj/canvas/issues/35)?

**Comment by orenguyster** [comment]
Thank you, now the post has been saved but for some reason i cant see the pic on the front page and when im editing the post the image and the text bellow disappeared

**Comment by austintoddj** [comment]
@orenguyster If you check in your database, has the raw data been persisted? Or are you seeing it wipe the content?

**Comment by poklin** [comment]
Hi @austintoddj ,

Actually I having the same issue again after merging the TNTSearch. My current error is below
"TNTIndexer.php line 348: Maximum execution time of 60 seconds exceeded"

**Comment by austintoddj** [comment]
@nticaric Any way thoughts on why TNTSearch would be doing this?

**Comment by foxted** [comment]
Seems like a memory problem. Maybe a script is taking too long to execute. Would have to look through the code to figure out what is taking so long.

**Comment by austintoddj** [comment]
@poklin @orenguyster I'm implementing a new editor into Canvas called [SimpleMDE](https://simplemde.com), which will effectively replace Summernote and all it's capabilities, including the image upload button that I believe is causing you issues.

**Comment by austintoddj** [comment]
@poklin @orenguyster Let me know if [v2.1.0](https://github.com/austintoddj/canvas/releases/tag/v2.1.0) fixes it for you.

**Comment by orenguyster** [comment]
Hi @austintoddj,

First thank you so much for this support.

with the old editor
I checked how it's look on the database and it's look something like that: https://i.imgur.com/2pdypef.png.

When edit the post again the image and the bellow content disappears. 

Second, when i saved the image, in the posts index page its look like it's messing with the divs:  https://i.imgur.com/1TyoxC3.png
You can see that the bellow image is bigger and the sidebar moved down, also at the post page.
https://i.imgur.com/Z3On3p4.png

I'll try the new editor

Thanks again.

**Comment by austintoddj** [comment]
Hm, that may be an inconsistency with the way Summernote handled image uploading. I would advise the new editor SimpleMDE, that will retain strict Markdown standards and should take care of your issue. I'll close this one out, but if you run into another problem feel free to open another! :)
