### ISSUE TITLE
Laravel debugbar breaks image uploads

### ISSUE THREAD

**Issue by JeremyChb** [austintoddj/canvas#890]
After uploading the image, saving request get a 500 internal server error : 

![image](https://user-images.githubusercontent.com/13405982/98965289-2b392c80-250a-11eb-8a13-3f1c286d6e0d.png)

Seems like instead of only the image path the request try to save a lot of html
![image](https://user-images.githubusercontent.com/13405982/98965404-4ad05500-250a-11eb-8865-9f582dabd26a.png)
it continues like that on more than 55 000 chars of html

**Comment by austintoddj** [comment]
Not able to replicate this on my end. Is there anything special about your setup that may be different from the steps in the Readme?

**Comment by JeremyChb** [comment]
Not at all.

I tried on drag and drop or click to select a file and that's the same result : 

![image](https://user-images.githubusercontent.com/13405982/98981775-b4f2f500-251e-11eb-82dc-7c5e84d492b8.png)

The value set ont the field is broken.
I'm using the last version of Canvas.

**Comment by JeremyChb** [comment]
I found how to fix.

The problem is located there : 
![image](https://user-images.githubusercontent.com/13405982/98991716-867c1680-252c-11eb-9cdd-45a6ff539628.png)
With that syntax nothing ensure that there'll not be any layout or something else added.

I suggest to replace that by : 
![image](https://user-images.githubusercontent.com/13405982/98991826-add2e380-252c-11eb-94b5-9713dcf3ea7a.png)

It's located in the `UploadsController->store()` function

**Comment by austintoddj** [comment]
What browser are you experiencing this in? Since I haven't seen this before, I'm just wondering what's trying to attach all that extra code.

**Comment by JeremyChb** [comment]
Last version of google chrome.

Laravel 8 with these packages : 

https://github.com/barryvdh/laravel-ide-helper
https://github.com/barryvdh/laravel-debugbar
https://github.com/l-lin/font-awesome-animation
https://github.com/blade-ui-kit/blade-ui-kit
https://github.com/goldspecdigital/laravel-eloquent-uuid
https://github.com/spatie/laravel-view-models

**Comment by austintoddj** [comment]
And just to explore all the options, have you tried with various different images? Just wondering if something is attached to the file somehow.

**Comment by JeremyChb** [comment]
Yes, with many images picked randomly on internet

**Comment by austintoddj** [comment]
Ok, I'll dig more into it this weekend and see what I can find.

**Comment by JeremyChb** [comment]
Thank you :)

**Comment by mukarramkhalid** [comment]
Just a heads up. 

This is happening due to Laravel debug bar. 

If your app is in production or Laravel debugbar is disabled, then it works fine. 

Problem is that when you upload the image, the API returns image path and name. If debug bar is enabled, the response includes all the debug output as well. 

Canvas considers this whole output as a file path/name, which is too long for the column where it saves it eventually.

**Comment by austintoddj** [comment]
Thanks for the clarity on this issue @mukarramkhalid. I'll get a "Known issues" list started and make sure this gets on there and is visible to anyone who looks.

**Comment by austintoddj** [comment]
@mukarramkhalid I just opened a [discussion here](https://github.com/austintoddj/canvas/discussions/922) to detail the issue. If you wouldn't mind, would you care to drop your solution in as an answer, and I'll go ahead and mark it Answered?

That way I can close this issue out and it'll be there for anyone else having the same problem.
