### ISSUE TITLE
Track visits by taking unique views based on IP and agent.

### ISSUE THREAD

**Issue by JapSeyz** [austintoddj/canvas#891]
Hi,

We use a separate frontend which does not use Laravel Sessions. To get stats somewhat working, we're manually throwing the `new PostViewed($post);` event. However, it always tracks both a view and a visit, because it can't save anything to session.

Would you be interested in a PR which allows us to calculate visits based on a unique group value between IP, Agent and the Day?

Which would give one visit a day, when using the same IP and Agent.

**Comment by austintoddj** [comment]
Thanks for the offer! 

So, right now visits are tracked by checking an IP in a 24 hour period. Is your suggestion to increase the check itself to include the agent? 

My only thought with that is the fact that agent strings are so long, it'd be tough to do comparisons on  them.

However, if you want to submit a PR for what you're thinking, I'd be more than happy to take a look.

**Comment by JapSeyz** [comment]
Frontends that dont use Laravels Session, (like ours dont), will always track both a visit and a view, because it cannot save `viewed_posts` to the session. (because the Backend is only an API, and the frontend just works by off-of REST requests, there's never any session data available).

I would simply take all the saved views, and group them into `visits` by grouping IP, Agent and Day.

I do see the issue w/ the agent strings, and perhaps it'd be better to do by IP and day only.
The best solution in my opinion would be an additional table which holds a more normalised user-agent (IE 11 etc), by and reference it via an ID. 

I hope it makes sense?

**Comment by austintoddj** [comment]
> Frontends that dont use Laravels Session, (like ours dont)

Not completely sure about this. Since this package is intended to be dropped into a Laravel app, it _should_ always have access to sessions, regardless of the FE architecture. The session data should be coming from the BE, not the FE.

Maybe I'm not understanding your implementation enough.

**Comment by iMusicJJ** [comment]
> > Frontends that dont use Laravels Session, (like ours dont)
> 
> 
> 
> Not completely sure about this. Since this package is intended to be dropped into a Laravel app, it _should_ always have access to sessions, regardless of the FE architecture. The session data should be coming from the BE, not the FE.
> 
> 
> 
> Maybe I'm not understanding your implementation enough.

We have Laravel as an api, and the frontend is completely separate, just fetching data from the Api.

This doesn't allow the use of sessions, unfortunately.

**Comment by austintoddj** [comment]
Aha, ok that makes sense. 

If you want to go ahead and submit a PR for what you're thinking, I'll take a look!
