### ISSUE TITLE
Command "canvas:ui" is not defined.

### ISSUE THREAD

**Issue by opang8** [austintoddj/canvas#897]
I have successfully installed this canvas, but when I type php artisan canvas: ui in my text editor. I instead get the command "canvas: ui" undefined.

   Do you mean one of them?
       canvas: digest
       canvas: install
       canvas: publish
like this

so how can i use the frontend on laravel 7 version?

![image](https://user-images.githubusercontent.com/68223424/100192999-88c77300-2f25-11eb-92d8-a5c40e61882c.png)

**Comment by austintoddj** [comment]
@opang8 What version of Canvas are you using?

**Comment by nfandrich** [comment]
Canvas version 5.4. Issue still existing!

**Comment by austintoddj** [comment]
The 'canvas:un' command was introduced in [v6.0.2](https://github.com/austintoddj/canvas/releases/tag/v6.0.2)

Once you upgrade the package, you'll have access to the command.
