### ISSUE TITLE
Need help on setting up my path in nested directory structure

### ISSUE THREAD

**Issue by whysoawesome0207** [austintoddj/canvas#898]
I am following the contribution guide, I just set up my project in the nested directory structure as I am in development mode so I just not set up my virtual host as well.

For e.g.,

~~~
- project
   - blog-laravel-app
   - canvas-repo
~~~

I just set up everything only my assets path is mismatching. I am just seeing a white screen nothing else on debugging I am able to reproduce that it's looking for the `http://localhost` and my project is in 'http://localhost/blog-laravel-app/public/canvas'. Even all API routes are also 404.

Is there any way to change the path just for development purposes?

**Comment by whysoawesome0207** [comment]
Since not getting any replies ended up setting a virtual host.

**Comment by austintoddj** [comment]
Sorry I didn't get a chance to respond to this. I'm glad you figured it out so quickly though, let me know if I can help out with anything else.
