### ISSUE TITLE
Opacity of code blocks in dark mode

### ISSUE THREAD

**Issue by whysoawesome0207** [austintoddj/canvas#899]
I just observed the following point,

- Well, I just tested the code block and not able to see what is written in the code. Below I am sharing the screenshot.

![Screenshot from 2020-12-01 15-14-57](https://user-images.githubusercontent.com/31669199/100723996-68495e00-33e8-11eb-84f3-ab255b05ee4e.png)

- When code block is in the very end, then not able to generate a new line or paragaph.

**Comment by austintoddj** [comment]
Thanks for catching this @whysoawesome0207. I'll tag it as a bug and get to it as soon as I can, unless you want to beat me to it and submit a PR 😉

**Comment by whysoawesome0207** [comment]
Currently, I can only work om weekend due to hectic schedule may be you are in winning zone. 😀

**Comment by austintoddj** [comment]
Since this deals with the 3rd party package [highlight.js](https://highlightjs.org/), there isn't much that can be done without some hacking. Closing this until a proper solution can be proposed and submitted.
