### ISSUE TITLE
Editing core files

### ISSUE THREAD

**Issue by samuelhgf** [austintoddj/canvas#900]
Hi, I was not able to find out how to edit migrations, models and other things...

Those files does not become available to customize ?

**Comment by austintoddj** [comment]
@samuelhgf This package does not publish those items as it'd make the upgrade path for future versions very unstable. 

Is there something in particular you were looking to customize?

**Comment by klaxurit** [comment]
Hi @samuelhgf  hi @austintoddj, thanks a lot for your work, your canvas is awesome XD.
I'm thinking about adding a comments/replys and like/dislike system to the canvas(in vuejs of course), what do you think about it ?

**Comment by austintoddj** [comment]
@klaxurit Thanks for the kind words.

If you want to try adding that to the `canvas-ui` portion of the project, feel free to submit a PR with your changes and I'd be more than happy to take a look!
