### ISSUE TITLE
Problem on showing published posts

### ISSUE THREAD

**Issue by workfransiskusferdian** [austintoddj/canvas#904]
I find that published posts on canvas dashboard don't show although the updated_at field in db not null. the published post keep in the 'draft' and don't move on 'published'. I guess it causes by Post::published() method doesn't work properly, but I'm not sure yet. how can I fix this? Thank you

**Comment by austintoddj** [comment]
So even if the `updated_at` field is not null, it depends on the `published_at` field. Only published posts show up with stats.

**Comment by richard457** [comment]
What was the solution @workfransiskusferdian ??

**Comment by richard457** [comment]
> So even if the `updated_at` field is not null, it depends on the `published_at` field. Only published posts show up with stats.

yes, I manually added published_at date in DB still the post could not be published.
