### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by fozoholiver1** [austintoddj/canvas#908]
i had this issue while installing canvas in laravel 8 with laravel ui
 Problem 1
    - cnvs/canvas[v5.2.0, ..., v5.2.5] require illuminate/support ^5.6|^5.7|^5.8|^6.0 -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6
.x-dev] but these were not loaded, likely because it conflicts with another require.
    - cnvs/canvas[v5.3.0, ..., v5.4.0] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires cnvs/canvas ^5.2 -> satisfiable by cnvs/canvas[v5.2.0, ..., v5.4.0].

**Comment by austintoddj** [comment]
What version of Canvas are you installing?

**Comment by fozoholiver1** [comment]
please ,i just ran composer require austintoddj/canvas from the documentation

**Comment by austintoddj** [comment]
The latest version of Canvas is 6.x

Can you try updating the version you're installing and let me know if you still have issues with it?

**Comment by fozoholiver1** [comment]
okay, sir, maybe I didn't  explain the problem well, I haven't used this package before, my PHP version is  php8, laravel8, and laravel valet when i ran  `composer require austintoddj/canvas` i had that error, i tried to do update my compooser.js PHP version to suit the package requirements as such  ` "require": {
        "php": "^7.3|^8.0",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "doctrine/inflector": "^1.4|^2.0",
        "dragonmantank/cron-expression": "^3.0.2",
        "egulias/email-validator": "^2.1.10",
        "league/commonmark": "^1.3",............................`

**Comment by austintoddj** [comment]
Aha, got it.

The package doesn't yet support PHP8, but it will in the next release.

Hoping to have it out in just a couple days or less.

**Comment by austintoddj** [comment]
@fozoholiver1 Fixed in [v6.0.14](https://github.com/austintoddj/canvas/releases/tag/v6.0.14)

Let me know if you run into any issues!
