### ISSUE TITLE
Frontend language

### ISSUE THREAD

**Issue by hatasu** [austintoddj/canvas#909]
First of all thanks for your great work with Canvas!
Simple but great interface, easy to use. 

But I had a question:
How can I use translated texts in Frontend?

**Comment by austintoddj** [comment]
Thanks for the kind words!

You're talking about having localized content for the `canvas-ui` portion of it, correct?

**Comment by hatasu** [comment]
Yes, that's what i meant.

_resources\js\canvas-ui\components\PageHeaderComponent.vue_
![image](https://user-images.githubusercontent.com/4637592/102998151-e4861b80-4526-11eb-80e8-7b1f2ecf8205.png)

**Comment by austintoddj** [comment]
Unfortunately, that part of it just isn't done. I focused largely on translating the backend, but haven't done the frontend yet.
