### ISSUE TITLE
Get Popular Posts

### ISSUE THREAD

**Issue by oldwestern** [austintoddj/canvas#910]
Is it possible to get posts and order by views or visits?

**Comment by austintoddj** [comment]
Do you mean in the /posts section of the package?

**Comment by oldwestern** [comment]
Yes, so currently I would get posts and order by published:

`Post::published()->orderByDesc('published_at')->simplePaginate(10)`

Is there a way I can order by views or visits?

**Comment by austintoddj** [comment]
You could join the View or Visit table, select the count, and then simply order by the greatest count. At least that's what I'd try to do, but I'm AFK at the moment.

**Comment by oldwestern** [comment]
Alright I got it to work, just in case anyone else comes searching for the answer the following worked for me:

`Post::published()->leftJoin('canvas_views', 'canvas_posts.id', '=', 'canvas_views.post_id')
      ->selectRaw('canvas_posts.*, count(canvas_views.post_id) as PostCount')->orderByDesc('PostCount')
      ->groupBy('canvas_posts.id')->simplePaginate(10)`

Thank you for the assistance and your continued support on this project!
