### ISSUE TITLE
Draft posts are being displayed under the author's profile

### ISSUE THREAD

**Issue by FoxRocks76** [austintoddj/canvas#912]
I've got two posts, one is published and one is a draft. When I'm logged in I can confirm this by selecting posts from the admin menu, it clearly defines and separates the published from the drafts. On the front end, when clicking on the published post, then clicking on the authors profile, it lists my draft post. I logged out and then tried again, thinking it was because it recognized me as the author, however it is still being displayed.

**Comment by austintoddj** [comment]
Thanks for bringing this up @FoxRocks76. I'll take a look first thing in the morning.

**Comment by austintoddj** [comment]
Fixed in [v6.0.16](https://github.com/austintoddj/canvas/releases/tag/v6.0.16)
