### ISSUE TITLE
The GET method is not supported for /logout

### ISSUE THREAD

**Issue by prafful98** [austintoddj/canvas#915]
On clicking Sign Out in Laravel 8 + Jetstream setup I am getting this error
```
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: POST.
http://127.0.0.1:8000/logout
```

**Comment by austintoddj** [comment]
Are you able to access the app via the app url defined in your `.env` file?

**Comment by prafful98** [comment]
Thank you so much @austintoddj for the quick fix, I am love Canvas

**Comment by ilhamAdhim** [comment]
Excuse me, i know the issue is closed already. But i encounter this error as well. I tried updating the canvas with composer require but it is not solved yet. How can i fix this?

**Comment by austintoddj** [comment]
@ilhamAdhim Are you customizing the path or domain?
