### ISSUE TITLE
`RedirectIfAuthenticated` middleware is being hit when I try to visit /canvas

### ISSUE THREAD

**Issue by GigaMick** [austintoddj/canvas#917]
When I try to visit /canvas on my app I am redirected to /dashboard.

This is url that is fired when the `RedirectIfAuthenticated` middleware is triggered.

I tested this by changing the `RedirectIfAuthenticated` redirect location and then /canvas took me to the new gibberish location I entered.

My canvas users table has nothing in it. I believe this is the problem, is there a way to generate a new canvas admin user?

Using version 6.0.7 on Laravel 7.29.3 and php7.4

**Comment by austintoddj** [comment]
Check [this section](https://github.com/austintoddj/canvas/blob/master/.github/UPGRADE.md#setting-up-a-user) of the upgrade guide and it'll help you set up a new user.
