### ISSUE TITLE
Upload preview

### ISSUE THREAD

**Issue by foxted** [austintoddj/canvas#92]
1. There is a 404 error in this template `resources/views/backend/upload/partials/modals/files/preview.blade.php` trying to load an non-existing image on page load. Obviously this modal is used for the file preview. A simple fix might be to create a fake transparent pixel gif to avoid the 404
![screen shot 2016-08-06 at 12 56 14 am](https://cloud.githubusercontent.com/assets/1385160/17455566/a548f64e-5b70-11e6-8d5d-9f852e563a7d.png)

2. The preview modal should also be triggered by clicking the name of the file. For now, only the magnifying glass icon can trigger it.

**Comment by austintoddj** [comment]
@foxted Does this fix your issue?

**Comment by foxted** [comment]
@austintoddj It does, thanks.
