### ISSUE TITLE
Need Some Info Regarding Disqus

### ISSUE THREAD

**Issue by whysoawesome0207** [austintoddj/canvas#926]
Hi @austintoddj,

Recently i just added Disqus comment manually to my site. But when i see the older PRs there is PR regaarding the Disqus comment,
https://github.com/austintoddj/canvas/pull/3

But, i didn't see any documentation. Is this feature removed.

**Comment by austintoddj** [comment]
It used to be a feature in an earlier version of the package. At this time, the frontend scaffolding doesn't provide a commenting feature like that.
