### ISSUE TITLE
Regarding date issue in posts

### ISSUE THREAD

**Issue by whysoawesome0207** [austintoddj/canvas#927]
## Version
Canvas v6.0.18

## Issue
I just notice the thing that whenever I just publish a post the dates are correct in front. But when I started editing the post the date displaying in the frontend is one or two days back.

For e.g. I just publish the post today i.e. 31st Jan 2021 in the frontend is displaying correctly but when I edited the post the date in the frontend is 26 Jan 2021. How?

Now to resolve the date I just again put the draft and then again publish.

**Comment by austintoddj** [comment]
Is the issue you're seeing the backend portion of Canvas, or the frontend `canvas-ui` section?

**Comment by whysoawesome0207** [comment]
Frontend portion `canvas-ui`. Whenever i edit a published post, its autosave and in the `canvas-ui` its not am exact date. To fix that i need to put my post as a draft and then republished.

**Comment by whysoawesome0207** [comment]
I just shared info. Do you want more info?

**Comment by austintoddj** [comment]
@whysoawesome0207 I can't seem to replicate a bug with this. I published a post, updated it, and saw the dates appropriately change both in /canvas and in /canvas-ui.

Is it perhaps a timezone issue that you've got set in your base Laravel app?

**Comment by whysoawesome0207** [comment]
OK! Give me some time, i will share you my screencast.
