### ISSUE TITLE
VueMeta not updating the meta info on the page

### ISSUE THREAD

**Issue by scvn1** [austintoddj/canvas#930]
For some reason, the VueMeta package is not updating the meta values when a page is shown even if there are values in the `metaInfo()`.

**Comment by austintoddj** [comment]
Thanks for bringing this up @scvn1. Have you customized the `canvas-ui` assets, or are they freshly published by the package?

**Comment by scvn1** [comment]
Yes, very minimally customized though. Just a few bits of HTML within the template changed.

**Comment by austintoddj** [comment]
@scvn1 Pushed out the latest patch version. To see what changed, grab the latest `ui/views/ShowPost.vue` file. Let me know if you have any other questions!

**Comment by scvn1** [comment]
I see the issue. It is in fact writing the meta tags, but as duplicates at the bottom of the page instead of overwriting the site default values.

Example:
![image](https://user-images.githubusercontent.com/60627569/106955136-a9f8cc80-66e9-11eb-8d1d-58939870a2b3.png)

**Comment by austintoddj** [comment]
Ack. Ok I'll re-open and try to get a fix out tomorrow.

**Comment by scvn1** [comment]
Appreciate it!

**Comment by sasafister** [comment]
Is this fixed? I have the same problem

**Comment by austintoddj** [comment]
@sasafister Not yet, but I hope to get a fix out this week.
