### ISSUE TITLE
There is no "New Post" button

### ISSUE THREAD

**Issue by syvbyen** [austintoddj/canvas#933]
I actually have two problems, but the first one I fixed manually (maybe I'm doing something wrong). I'm listing them together in case they affect each other somehow.

1. When I make a new user with
`php artisan canvas:user admin --email=email@example.no`

I then get an error when I go to _www.url.com/canvas_:

> Argument 1 passed to Canvas\Canvas::enabledDarkMode() must be of the type int, null given,

My manual fix is going into my own database and setting it to "0", then I get the same error with locale. And again I just set it manually. That's fine, a little annoying but fine.

2. Then when I log in there is no **New Post** button. This is how it looks where I'm guessing it's supposed to be a button

![image](https://user-images.githubusercontent.com/62508550/107054294-3a114180-67d0-11eb-9513-cb0d4ae94359.png)

(It's the role _editor_ because I tried changing it too see if that changed anything)

**Comment by austintoddj** [comment]
Good catch here. I just pushed out a [release](https://github.com/austintoddj/canvas/releases/tag/v6.0.22) to fix the dark mode and locale bugs. 

The **New Post** button on the other hand is just a UX thing. It's actually only accessible on the `/stats` and `/posts` pages. I can understand if that's a bit too hidden for folks, but I wanted to make it consistent with the way that you create Tags and Topics. All are accessible from their list pages.
