### ISSUE TITLE
Not an issue. Can we add text alignment options to text editor like we have in ckeditor etc?

### ISSUE THREAD

**Issue by usamapatel** [austintoddj/canvas#934]
No an issue. Can we add text alignment options to text editor like we have in ckeditor etc?

**Comment by austintoddj** [comment]
That's a good idea @usamapatel. Since this isn't an issue at the moment, would you mind dropping your suggestion here on #919 to keep it all together? Thanks!

**Comment by usamapatel** [comment]
@austintoddj Done

**Comment by austintoddj** [comment]
Thanks @usamapatel!
