### ISSUE TITLE
Installing Canvas-UI in Laravel 8 npm errors

### ISSUE THREAD

**Issue by joaquimpsoares** [austintoddj/canvas#935]
I follow the instructions to install web-mix 6 here: 
https://laravel-mix.com/docs/6.0/upgrade

And in the section "Update Your NPM Scripts"

I also had to update scripts section in package.json like suggested in the previous section:

Before
"scripts": {
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
}

After
"scripts": {
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "production": "mix --production"
}

Once update laravel mix  to version 6 and updated scripts I was able to run npn run dev.

**Comment by austintoddj** [comment]
Yep, totally right with what you did there. Since this package needs to be able to support both versions of Laravel (those with Mix6 and those without), I dropped [a solution here](https://github.com/austintoddj/canvas/discussions/920#discussioncomment-296402) to offer some clarity.
