### ISSUE TITLE
Canvas documentation 

### ISSUE THREAD

**Issue by keithzano** [austintoddj/canvas#937]
Hi I pretty new to programming and I wanted to try out canvas with my own front but I cant seem to find any documentation beyond installing.

**Comment by austintoddj** [comment]
Well, welcome! Glad you're new to programming, I hope you find joy and satisfaction in it.

How familiar are you with Laravel/Vue?

**Comment by keithzano** [comment]
Not quite I want to use the blade template engine

**Comment by austintoddj** [comment]
Have you successfully installed Canvas and run the `canvas:ui` Artisan command?

**Comment by NeonOdyssey** [comment]
I would like to 1up this. 
Coming back to Canvas after a long time I have now found that even the example code on how to set up your own Posts and post pages has disappeared.

I can completely understand that you are wanting people to use `$php artisan canvas:ui`. However, this is a huge turn away as there is no documentation to help developers develop their own front end to match their existing website.

At the moment I am having to rip apart the `CanvasUiController` to figure out some basic components like listing published posts etc.

**Comment by austintoddj** [comment]
@NeonOdyssey Could you give me an example of what a useful setup would look like for you? Happy to adjust the docs to make it easier in this area.

**Comment by NeonOdyssey** [comment]
even if it was a separate page with a list of how to do the following:
- get all published posts
- - get post content, title, date, user info, etc of a specific post
- list all tags
- - list all posts within a tag
- list all topics
- - list all posts within a topic
(Just how the API does things)
I have managed to do this all however I think this would extremely help new developers who are wanting to get setup.

**Comment by austintoddj** [comment]
Really helpful, thanks @NeonOdyssey. I'll get some API specs in the readme.

**Comment by austintoddj** [comment]
@NeonOdyssey Got some docs pushed out today. https://github.com/austintoddj/canvas#api

**Comment by NeonOdyssey** [comment]
@austintoddj that's awesome to see 😄 
This will help me alot later down the line, and I'm sure will help others as well.
