### ISSUE TITLE
[Suggestion] Import from Medium.com

### ISSUE THREAD

**Issue by foxted** [austintoddj/canvas#94]
It would be nice to be able to import posts from Medium.com when migrating to Canvas.

https://medium.com/developers/welcome-to-the-medium-api-3418f956552#.h1llq8wn9

**Comment by austintoddj** [comment]
I'll look into that. Never used Medium before, but heard good things about it. I'll see what we can do with this.

**Comment by foxted** [comment]
Maybe a simple Artisan command with Medium API keys in `.env` file and the import would populate the posts table.

**Comment by austintoddj** [comment]
I'll take a look into this right away @foxted. Looks like it'd be a great feature to ship with Canvas.

**Comment by austintoddj** [comment]
@foxted So exporting from Medium gives you an HTML file. Do you know of a good way to parse through that and prepare it to be imported into Canvas?

**Comment by foxted** [comment]
Even going through the API?

**Comment by austintoddj** [comment]
Hm, let me check more on that. Found a bit of documentation, let me see what else I can find.

**Comment by fergthh** [comment]
Through Api it seems that you can not retrieve the content of publications, just list them with the following information: title, description, url and image.

**Comment by austintoddj** [comment]
That's what I've been seeing so far as well.

**Comment by austintoddj** [comment]
Going to close this one out for now, since it doesn't look like Medium gives us a good way to access their posts in a proper format to apply them to Canvas. If anyone else can find a way to implement this, I'll by all means open this back up and merge in a PR.
