### ISSUE TITLE
Can not upload avator

### ISSUE THREAD

**Issue by attitudefx7** [austintoddj/canvas#947]
When i tried to upload avator, I got a bug like this
![image](https://user-images.githubusercontent.com/39052856/110447935-b06cd080-80fb-11eb-86cf-5b1c7504bc3e.png)

please help me!

**Comment by austintoddj** [comment]
@attitudefx7 Looks like that's just the request. Could you post the response you're getting?

**Comment by attitudefx7** [comment]
That was a bad request url like this : **https://api/uploads**.   The doman gone away.   So I got nothing from response.

**Comment by austintoddj** [comment]
Aha, apologies. Looked at it too quickly.

Do you have a domain _and_ a path set up in your .env file?
