### ISSUE TITLE
issue with canvas-ui / by tags / by topics

### ISSUE THREAD

**Issue by venixx04** [austintoddj/canvas#956]
I have installed canvas-ui:

1- when I select the index page, everything is fine, the posts are displayed.
2- however when I select a topic or a tag, no post is displayed!

Console browser :
canvas-ui.js:102306 [Vue warn]: Error in render: "TypeError: Cannot read property 'name' of undefined"
found in
---> <ShowTag> at resources/js/canvas-ui/views/ShowTag.vue
       <Root>

canvas-ui.js:103573 TypeError: Cannot read property 'name' of undefined
    at canvas-ui.js:95688
    at Proxy.renderList (canvas-ui.js:104313)
    at Proxy.render (canvas-ui.js:95605)
    at VueComponent.Vue._render (canvas-ui.js:105228)
    at VueComponent.updateComponent (canvas-ui.js:105746)
    at Watcher.get (canvas-ui.js:106159)
    at Watcher.run (canvas-ui.js:106234)
    at flushSchedulerQueue (canvas-ui.js:105990)
    at Array.<anonymous> (canvas-ui.js:103665)
    at flushCallbacks (canvas-ui.js:103591)

2- is there any way to rename canvas-ui to blog for example

Thanks

**Comment by austintoddj** [comment]
To update the path for the `canvas-ui` views, you'll need to update:

- Line 30 of `resources/js/canvas-ui/app.js`
- Line 25 of `resources/js/canvas-ui/mixins/base.js`
- Line 48 of `resources/js/canvas-ui/routes.js`
- `Route::prefix('canvas-ui')` in `routes/web.php`

After that, re-compile the assets and you should be all set.

**Comment by foutesting** [comment]
thank you. I modified the standard path following the modifications and it works. However, I always get an error when I select a tag or a topic. No post is displayed. There is a problem with js/canvas-ui.js

Console browser :

canvas-ui.js:102266 [Vue warn]: Error in render: "TypeError: Cannot read property 'name' of undefined"
found in
---> <ShowTag> at resources/js/canvas-ui/views/ShowTag.vue
       <Root>

See file in attach


[canvas-ui-js.txt](https://github.com/austintoddj/canvas/files/6191585/canvas-ui-js.txt)

**Comment by austintoddj** [comment]
@foutesting Found the bug. Resolved it in the main app, but since you've already published the files, go ahead and update your controller with the same changes found here:

https://github.com/austintoddj/canvas/commit/661abf76105905f5bda198e2c941048d85abbd0a

**Comment by foutesting** [comment]
Great. It work fine. Thanks
