### ISSUE TITLE
Posts are not published

### ISSUE THREAD

**Issue by webhaikal** [austintoddj/canvas#961]
Even when clicking publish post, and confirming that the published_at field is not null, posts are still shown as draft on a fresh install using Laravel 8 and latest Canvas.

**Comment by austintoddj** [comment]
Are there any console or network errors when you do that?

**Comment by YveOms** [comment]
@webhaikal I have encountered the same problem. Even after clicking publish, the post is just saved as a draft and is not published.

I am using PHP 7.4.16, and canvas v6.0.29 on Windows 10 Xampp Environment

**Comment by YveOms** [comment]
First, lets write a test post

![image](https://user-images.githubusercontent.com/28395700/118028521-05091380-b318-11eb-9e50-d59fe44acb06.png)

Then After clicking on publish now, and we go back to drafts, it is still there

![image](https://user-images.githubusercontent.com/28395700/118028679-32ee5800-b318-11eb-963f-c5abf106890d.png)

**Comment by austintoddj** [comment]
@YveOms Are there any console or network errors when you do that?

**Comment by YveOms** [comment]
Hey @austintoddj . Thanks or pointing out the console thing. I am fairly new to Laravel, and I went back to their website and used the command `php artisan serve --port=8080` to serve the app. And the Canvas Blog is now working perfectly.  The posts are actually being posted.

As for @webhaikal, if you don't see your posts immediately, check your UTC offset of your location and adjust the post time correctly.

**Comment by lordz123** [comment]
the `php artisan serve --port=8080` not helping m instead theres an error in the console 
all the post are save as draft

![image](https://user-images.githubusercontent.com/27280478/183294194-a38b0c39-3673-4aa0-8ea0-fbfff0bcc675.png)

**Comment by kusman28** [comment]
Save problem. How did u solve guys
