### ISSUE TITLE
Wizard Installation

### ISSUE THREAD

**Issue by CodexOS** [austintoddj/canvas#962]
Hello @austintoddj,

Have you ever considered adding a wizard installer for people that would like to install it without doing it through commands?

**Comment by austintoddj** [comment]
Can't say I've put too much thought in that. Would love to review a PR if you wanted to take a stab at it!

**Comment by CodexOS** [comment]
I'm really new to coding so I'm not too familiar with Laravel, but I really like to use your project to start a Blog website and was interested in just setting it up with a wizard and learn from there.

**Comment by austintoddj** [comment]
Makes sense, and welcome! 

If you have any trouble setting Canvas up or just have some general questions, let me know and I'll help you out.

https://twitter.com/@austintoddj
