### ISSUE TITLE
SEO concerns

### ISSUE THREAD

**Issue by farishrf** [austintoddj/canvas#990]
Hi, my blog is running on Canvas, and it isn't showing in Google search, 
I added the website to the Google search console, it's been 2 months, and yet no search appearance.
are there any known SEO problems with this blog software?

Thanks.

**Comment by austintoddj** [comment]
Could you post a snippet of what the <head> element contains on some of your blog pages?

**Comment by farishrf** [comment]
Not sure what you mean, 
but this is a post from the website: https://farishrf.sa/posts/beginning

**Comment by austintoddj** [comment]
There aren't any SEO problems with the package as it is. From looking at your post you shared, I do see proper meta fields that should be picked up by Google:

<img width="814" alt="Screen Shot 2021-08-18 at 8 14 30 AM" src="https://user-images.githubusercontent.com/8037011/129904488-ad679d76-6a81-444a-b7cf-ba0b9f991e34.png">

As far as _why_ it hasn't been appearing in your Google Search Console, I'd check in on some of the solutions provided here:

https://support.google.com/webmasters/thread/12398709/no-data-showing-on-google-console
