### ISSUE TITLE
No "publish" button in dropdown

### ISSUE THREAD

**Issue by GigaMick** [austintoddj/canvas#993]
As It says on the tin. I have created a new post, it is marked as draft and the published_at field in the DB is null

<img width="973" alt="Screenshot 2021-09-05 at 17 04 30" src="https://user-images.githubusercontent.com/22120297/132133545-95c5befb-b66b-4d94-8c91-0d2872205b63.png">

As you can see there is no option to "publish". There is a VERY HIGH chance that I'm being dumb here, so all help appreciated.

**Comment by GigaMick** [comment]
This seemed to only be a problem in local...

**Comment by austintoddj** [comment]
@GigaMick Assuming you got this all figured out, but looks like your user just needs the [role of Editor or Admin](https://github.com/austintoddj/canvas#roles--permissions).

**Comment by richard457** [comment]
@GigaMick I still have this issue and I migrated from old package can you help?

**Comment by austintoddj** [comment]
@richard457 What version of the package are you using?
