### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [austintoddj/canvas#996]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by austintoddj** [comment]
@JamieSlome Sure thing, I'll get one in the repo shortly.

Go ahead and shoot me a message at austin.todd.j@gmail.com

**Comment by b1nslashsh** [comment]
Hey , @austintoddj 

Hope you received a mail from hundr.dev haven't?

Please let me know your thoughts about the disclosure 

Thanks ,
Muhaimin

**Comment by austintoddj** [comment]
@b1nslashsh I responded.

**Comment by b1nslashsh** [comment]
> @b1nslashsh I responded.

I think maybe you do somthing wrong or it didn't worked , I didn't get any response for this 🙂

https://www.huntr.dev/bounties/aa8ec091-4d39-4cdc-9a3c-26cf95a35b46/

https://www.huntr.dev/bounties/5392edf3-3278-4100-aeee-08a68995e83d/

Feel free to have a look 

Thanks,

**Comment by austintoddj** [comment]
Marked it as valid earlier in the day. @JamieSlome all good on your end?

**Comment by JamieSlome** [comment]
@austintoddj - all good on our side!

Once you have patched the vulnerabilities in the repository, feel free to `confirm the fix` for each.

-- Jamie
